### PR TITLE
fix error with unreachable binary patterns

### LINKED ISSUE #5286: Bug in exhaustiveness matching
The compiler incorrectly considers the second pattern here as unreachable:
```gleam
pub fn main(x) {
   case x {
    <<_, "==">> -> 1
    <<_, _,"=">> -> 2
//  ^^^^^^^^^^^^ Unreachable
    _ -> 3
  }
}
```
I'm working on this!

### PR DESCRIPTION
**Pull request by giacomocavalieri**
This PR closes #5286 

---
- [X] The changes in this PR have been discussed beforehand in an issue
- [X] The issue for this PR has been linked
- [X] Tests have been added for new behaviour
- [X] The changelog has been updated for any user-facing changes

### CODE REVIEW

File: compiler-core/src/javascript/tests/case.rs [hunk 1]
```diff
@@ -842,22 +842,6 @@ pub fn go(x, y) {
...
-#[test]
-fn interfering_string_pattern_fails_if_succeeding() {
-    assert_js!(
-        r#"
-pub fn wibble(bits) {
-  case bits {
-    <<"aaa", 0, _:bits>> -> 1
-    // If the first one fails, we know this one won't match, so it won't appear
-    // in the final else branch!
-    <<_, "aa", 1, _:bits>> -> 2
```
Comment (giacomocavalieri) [inline compiler-core/src/javascript/tests/case.rs:854]: This test and the other one in this file I removed were actually wrong! If the first pattern doesn't match the second one actually has a chance of matching. For example if the input were `<<"baa", 1>>` it would not match with the first branch but it would with the second. Don't know how I couldn't notice this 😅

**Review by lpil — APPROVED** [review]
Beautiful, thank you!!
