### PR TITLE
fix(lsp): uri to module name fails on Windows

### LINKED ISSUE #1595: LSP: uri to module name fails on Windows

### PR DESCRIPTION
**Pull request by HarryET**
Fixes #1595 by using a built in method on `Uri` to convert it to a `PathBuf`

### CODE REVIEW

File: compiler-cli/src/lsp.rs [hunk 1]
```diff
@@ -715,6 +717,45 @@ impl LanguageServer {
     }
 }
 
+#[cfg(target_os = "windows")]
+fn uri_to_module_name(uri: &Url, root: &Path) -> Option<String> {
+    let mut uri_path = decode(&*uri.path().replace('/', "\\"))
```
Comment (lpil) [inline compiler-cli/src/lsp.rs:722]: What does the decode bit do here?

Comment (HarryET) [reply compiler-cli/src/lsp.rs:722]: For some reason parts of the path are URL encoded, for example the colon is shown as %3A which causes issues.
