### PR TITLE
Permit to define target specific functions without needlessly failing compilation for a different target

### LINKED ISSUE #2324: Permit deps with other-target only functions to compile
Not sure how to title this because in a way it’s two issues. title could be fixed

## Problem(s)

1. If I import a javascript only dependency, using `@target(javascript)` and build for erlang, Gleam gives an error regarding that dependency not implementing a function in erlang.

2. If do the same as before but not import that javascript only dependency, I still get the same error even though I have not used the function.

## Steps to recreate the issue

1. `gleam new abc`
2. `cd abc`
3. `gleam add gleam_javascript`
4. `gleam build` 

> `error: Function without an implementation`

## Possible solutions

- In `gleam.toml` add an option to specify the target for a dependency. 
ex:
`gleam_javascript = { version = "0.6.0", target = "javascript" }`

- Build dependencies based on the target specified by the gleam.toml of the dependency. 
Assuming I add `gleam_javascript` and in its gleam.toml it says `target=javascript`, if I compile to erlang that dependency should not build

- Do not build a dependency if it’s not used. This could potentially speed up compile time by not building a dependency for no reason.

### PR DESCRIPTION
**Pull request by giacomocavalieri**
This closes #2324

To get a better feeling of the problem this PR addresses you can have a look at this code snippet:
```gleam
import gleam/io

@external(javascript, "foo", "bar")
pub fn js_only() -> Int

pub fn main() {
  io.println("I'm Erlang code!")
}
```
Trying to compile it on the Erlang target would fail with an error complaining that `js_only` doesn't have an implementation for the Erlang target. But this is needlessly limiting! Since `js_only` is never actually referenced by functions that are going to be compiled down to Erlang this code is still safe to compile and run!

After this PR compilation will only fail if someone tries to use a target-specific function in a code path that could be used in a different target:
```gleam
import gleam/io

@external(javascript, "foo", "bar")
pub fn js_only() -> Int

pub fn main() {
  io.println("I'm Erlang code!")
  js_only()
//^^^^^^^^^ error: this function doesn't have an implementation for the Erlang target.
}
```

### CODE REVIEW

File: compiler-cli/src/fs.rs [hunk 1]
```diff
@@ -182,7 +182,7 @@ impl CommandExecutor for ProjectIO {
             .args(args)
             .stdin(stdio.get_process_stdio())
             .stdout(stdio.get_process_stdio())
-            .envs(env.iter().map(|(a, b)| (a, b)))
+            .envs(env.iter().map(|(a, b): &(&str, String)| (a, b)))
```
Comment (lpil) [inline compiler-cli/src/fs.rs:185]: What's this for?

File: compiler-core/src/analyse.rs [hunk 2]
```diff
@@ -697,11 +732,19 @@ fn target_function_implementation<'a>(
     }
 }
 
-fn ensure_body_given(body: &Vec1<UntypedStatement>, location: SrcSpan) -> Result<(), Error> {
-    if body.first().is_placeholder() {
-        Err(Error::NoImplementation { location })
-    } else {
-        Ok(())
+fn is_empty_body(body: &Vec1<UntypedStatement>) -> bool {
```
Comment (lpil) [inline compiler-core/src/analyse.rs:735]: This is called a placeholder, not empty.

**Review by lpil — COMMENTED** [review]
Nice! DM'd you some Qs on discord. I'll do a full review after 🙏

File: compiler-cli/src/fs.rs (hunk 1 above)
Comment (giacomocavalieri) [reply compiler-cli/src/fs.rs:185]: I noticed CI was failing because the linter wanted me to remove this map, it's a false positive because it thinks it's the same as applying the identity function so I had to make the type explicit

File: compiler-core/src/analyse.rs (hunk 2 above)
Comment (abs0luty) [reply compiler-core/src/analyse.rs:735]: Isn't placeholder _used when parsing is incomplete or when a function body is missing_?

File: compiler-cli/src/fs.rs (hunk 1 above)
Comment (abs0luty) [reply compiler-cli/src/fs.rs:185]: You can alternatively use `#[allow(clippy::map_identity)]`

Comment (giacomocavalieri) [reply compiler-cli/src/fs.rs:185]: Ah I see, thank you! I'll revert this then

File: compiler-cli/src/compile_package.rs [hunk 3]
```diff
@@ -47,6 +47,7 @@ pub fn command(options: CompilePackage) -> Result<()> {
         &target,
         ids,
         ProjectIO::new(),
+        todo!("I'm not sure what should go here"),
```
Comment (giacomocavalieri) [inline compiler-cli/src/compile_package.rs:50]: @lpil I'm not sure what to do here, in the compiler-core package I had access to a `is_root` variable but here there's no such thing

File: compiler-core/src/type_/expression.rs [hunk 4]
```diff
@@ -10,28 +10,131 @@ use crate::{
...
+    ) -> Self {
         let mut hydrator = Hydrator::new();
+
         hydrator.permit_holes(true);
         Self {
             hydrator,
             environment,
+            // This will be narrowed down as the expression type is inferred
+            supported_targets: SupportedTargets::all(),
+            external_supported_targets,
```
Comment (lpil) [inline compiler-core/src/type_/expression.rs:137]: Why are these tracks independently? Seems they always get merged together before use so it can be simplified to a single value. This would also permit the `merge` method to be removed.

File: compiler-core/src/type_/expression.rs [hunk 5]
```diff
@@ -10,28 +10,131 @@ use crate::{
...
+            Target::Erlang => SupportedTargets {
+                erlang: true,
+                javascript: self.javascript,
+            },
+            Target::JavaScript => SupportedTargets {
+                erlang: self.erlang,
+                javascript: true,
+            },
+        }
+    }
```
Comment (lpil) [inline compiler-core/src/type_/expression.rs:88]: Favour mutation for these sorts of operations
```suggestion
    pub fn add(&mut self, target: Target) {
        match target {
            Target::Erlang => self.erlang = true,
            Target::JavaScript => self.javascript = true,
        }
    }
```

File: compiler-core/src/type_/expression.rs [hunk 6]
```diff
@@ -10,28 +10,131 @@ use crate::{
...
+
+    pub fn intersect(&self, targets: SupportedTargets) -> SupportedTargets {
+        SupportedTargets {
+            erlang: self.erlang && targets.erlang,
+            javascript: self.javascript && targets.javascript,
+        }
+    }
+
+    pub fn merge(&self, targets: SupportedTargets) -> SupportedTargets {
```
Comment (lpil) [inline compiler-core/src/type_/expression.rs:70]: This can be removed once external support was not tracked in a second data structure.

File: compiler-core/src/type_/expression.rs [hunk 7]
```diff
@@ -10,28 +10,131 @@ use crate::{
...
+            Target::JavaScript => SupportedTargets::javascript(),
+        }
+    }
+
+    pub fn intersect(&self, targets: SupportedTargets) -> SupportedTargets {
+        SupportedTargets {
+            erlang: self.erlang && targets.erlang,
+            javascript: self.javascript && targets.javascript,
+        }
+    }
```
Comment (lpil) [inline compiler-core/src/type_/expression.rs:68]: Perhaps this could be called `narrow` as that's the word used elsewhere in this PR.

Let's also use mutation here.

File: compiler-core/src/type_/expression.rs (hunk 4 above)
Comment (giacomocavalieri) [reply compiler-core/src/type_/expression.rs:137]: I think we have to keep track of those separately in the `ExprTyper`: when narrowing I have to perform this check 
```rust
self.supported_targets.narrow(new_targets);
if self.environment.target_support == TargetSupport::Enforced
   && !self.supported_targets
      .merge(self.external_supported_targets)
      .supports(self.environment.target) {
  // error this function has no supported targets and we must fail!
}
```
Supported targets get narrowed down starting from `SupportedTargets::all()`, the external targets, however, never change: imagine you had a function with an external js implementation that uses an Erlang-only function in its body:
```gleam
@external(javascript, "foo", "bar")
pub fn foo() {
  erlang_only()
}
```
If you had a single `supported_targets` field it would be narrowed down to just `SupportedTargets::erlang()` and you'd loose track of the fact that this function can actually support javascript as well. Now If you're compiling to JavaScript the check would fail:
```rust
self.supported_targets.narrow(new_targets);
if self.environment.target_support == TargetSupport::Enforced
   && !self.supported_targets.supports(self.environment.target) {
  // error this function has no supported targets and we must fail!
```
Because the body's supported target was narrowed down to just `Erlang` and you're not considering that you can still support JavaScript since you have an external implementation for that target.

Though the check could be written in a different way to make things a bit clearer and not rely on the merge function:

```rust
self.supported_targets.narrow(new_targets);
if self.environment.target_support == TargetSupport::Enforced
   && !(
     self.supported_targets.supports(self.environment.target)
     || self.external_targets.supports(self.environment.target)
   ) {
  // error this function has no supported targets and we must fail!
```

We would still need `merge` to merge the external targets and the body supported targets once the typer did its thing and record all the targets supported by the function, both those of its body and those with and external implementation.

Comment (lpil) [reply compiler-core/src/type_/expression.rs:137]: Ah I get it now, and you can't do that I originally said because that wouldn't give you the error at the point the non-supporting value is referenced. Thank you
