### PR TITLE
Generalize module constants

### LINKED ISSUE #2204: Constant's type is determined only once which causes strange errors
This code:

```gleam
import gleam/io
import gleam/result

pub fn with_smth(f: fn() -> a) -> a {
  f()
}

pub const with_smth2 = with_smth

pub fn main() {
  use <- with_smth2()
  Ok(Nil)
}

pub fn another() {
  use <- with_smth2()
  Nil
}
```

produces this error:

```
error: Type mismatch
   ┌─ /tmp/const_forward/src/const_forward.gleam:17:3
   │
17 │   Nil
   │   ^^^

Expected type:

    fn() -> Result(Nil, a)

Found type:

    fn() -> Nil
```

The problem is that when this constant is public and used in multiple files, these files fail in random order depending on slight code changes, and the error doesn't give enough context.

### PR DESCRIPTION
**Pull request by omprakaash**
This should fix #2204.

### CODE REVIEW

**Comment by omprakaash** [comment]
Modified call-graph to work with constants too. Just wanted to see if this was a good approach before modifying the tests for that as well.

File: compiler-core/src/analyse.rs [hunk 1]
```diff
@@ -157,24 +157,29 @@ pub fn infer_module<A>(
...
+            match definition {
+                Definition::Function(f) => {
+                    let statement = infer_function(f, &mut env, &mut hydrators, &name)?;
+                    working_group.push(statement);
+                }
+                Definition::ModuleConstant(c) => {
+                    let statement = infer_module_constant(c, &mut env, &name)?;
+                    working_group.push(statement);
+                }
+                _ => unreachable!("Only funtions and constants should be in a definition group"),
```
Comment (lpil) [inline compiler-core/src/analyse.rs:181]: Rather than crash at runtime let's have some type that is either a function or a module constant, making the invalid state impossible.

**Review by lpil — COMMENTED** [review]
Looks great!! Let me know when it's ready for a full review 💜

File: compiler-core/src/analyse.rs (hunk 1 above)
Comment (omprakaash) [reply compiler-core/src/analyse.rs:181]: Got it. Will refactor this.

**Review by lpil — APPROVED** [review]
Thank you!
