### PR TITLE
floating point values outside Erlang's floating point range should cause error

### LINKED ISSUE #4116: Illegal float literals crash when targeting Erlang
The following program crashes with a non-Gleam error when targeting Erlang.

```gleam
pub fn main() {
  let _ = 1.8e308
}
```

```
$ gleam run
  Compiling float_stuff
/home/ryan/projects/gleam/float_stuff/src/float_stuff.gleam:4:9: illegal float
/home/ryan/projects/gleam/float_stuff/src/float_stuff.gleam:4:16: syntax error before: '.'
/home/ryan/projects/gleam/float_stuff/build/dev/erlang/float_stuff/_gleam_artefacts/float_stuff.erl:4:2: function main/0 undefined
%    4| -export([main/0]).
%     |  ^

/home/ryan/projects/gleam/float_stuff/src/float_stuff.gleam:2:2: spec for undefined function main/0
%    2|   let _ = 1.8e308
%     |  ^

error: Shell command failure

There was a problem when running the shell command `escript`.
```

Here is the result of running `GLEAM_LOG=trace gleam run`:
[TRACE.txt](https://github.com/user-attachments/files/18270388/TRACE.txt)

(gleam 1.6.3)

### PR DESCRIPTION
**Pull request by massivefermion**
closes #4116

### CODE REVIEW

File: compiler-core/src/type_/error.rs [hunk 1]
```diff
@@ -1681,3 +1686,25 @@ pub fn check_javascript_int_safety(int_value: &BigInt, location: SrcSpan, proble
         problems.warning(Warning::JavaScriptIntUnsafe { location });
     }
 }
+
+/// When targeting Erlang, adds an error if the given Float value is outside the range
+/// -1.7976931348623157e308 to 1.7976931348623157e308 which is the allowed range for
+/// Erlang's floating point numbers
```
Comment (lpil) [inline compiler-core/src/type_/error.rs:1692]: Could we link to there these numbers were taken from in the Erlang docs please 🙏

File: compiler-core/src/type_/tests/errors.rs [hunk 2]
```diff
@@ -2655,3 +2655,18 @@ todo
...
+
+#[test]
+fn out_of_range_erlang_float_in_pattern() {
+    assert_error!(r#"let assert [1.8e308, b] = [x, y]"#);
+}
+
+#[test]
+fn out_of_range_erlang_float_in_const() {
+    assert_module_error!(r#"const x = 1.8e308"#);
+}
```
Comment (lpil) [inline compiler-core/src/type_/tests/errors.rs:2672]: Can we have tests for the negative case too please 🙏

**Review by lpil — COMMENTED** [review]
Awesome work! Thank you. I've left some small notes inline

File: compiler-core/src/type_/error.rs (hunk 1 above)
Comment (massivefermion) [reply compiler-core/src/type_/error.rs:1692]: I actually can't find them anywhere in the Erlang docs. I got them from [here](https://github.com/elixir-lang/elixir/blob/v1.18.1/lib/elixir/lib/float.ex).

**Review by lpil — COMMENTED** [review]
Could you rebase on main please? The changelog has a conflict 🙏

**Review by lpil — APPROVED** [review]
Thank you!!
