### PR TITLE
`gleam new` now creates the project directory using the confirmed project name

### LINKED ISSUE #5070: gleam new project name suggestion retains old name in newly created directory
# Expected behavior

The created directory should be named "testproject", as that is the new name of the project

# Actual behavior
The directory is named "gleam_testproject"

# Steps and code to reproduce the problem
```
$ gleam new gleam_testproject
We were not able to create your project as `gleam_testproject` has the
reserved prefix `gleam_`. This prefix is intended for official Gleam
packages only.

Would you like to name your project 'testproject' instead? [y/n]: y
Your Gleam project testproject has been successfully created.
The project can be compiled and tested by running these commands:

	cd gleam_testproject
	gleam test
```

# Versions for Gleam
```
$ gleam --version
gleam 1.13.0
```
(installed via ASDF)

# OS
Ubuntu 25.04

# Logs from running Gleam with the `GLEAM_LOG` environment variable set to `trace`
```
$ GLEAM_LOG=trace gleam new gleam_testproject
We were not able to create your project as `gleam_testproject` has the
reserved prefix `gleam_`. This prefix is intended for official Gleam
packages only.

Would you like to name your project 'testproject' instead? [y/n]: y
TRACE creating_directory path="[redacted]/gleam_testproject"
TRACE creating_directory path="[redacted]/gleam_testproject/src"
TRACE creating_directory path="[redacted]/gleam_testproject/test"
TRACE creating_directory path="[redacted]/gleam_testproject/.github"
TRACE creating_directory path="[redacted]/gleam_testproject/.github/workflows"
TRACE initializing git path="[redacted]/gleam_testproject"
TRACE checking_for_git_repo path="[redacted]/gleam_testproject"
TRACE git_repo_already_exists path="[redacted]/gleam_testproject"
Your Gleam project testproject has been successfully created.
The project can be compiled and tested by running these commands:

	cd gleam_testproject
	gleam test

 INFO Successfully completed
```

### PR DESCRIPTION
**Pull request by abs0luty**
- Closes #5070

### CODE REVIEW

File: compiler-cli/src/new.rs [hunk 1]
```diff
@@ -461,3 +473,52 @@ fn get_foldername(path: &str) -> Result<String, Error> {
...
+
+#[cfg(test)]
+pub(crate) struct AutoAcceptProjectNameSuggestionGuard(bool);
+
+#[cfg(test)]
+impl Drop for AutoAcceptProjectNameSuggestionGuard {
+    fn drop(&mut self) {
+        AUTO_ACCEPT_PROJECT_NAME_SUGGESTION.store(self.0, Ordering::SeqCst);
+    }
+}
```
Comment (lpil) [inline compiler-cli/src/new.rs:531]: Remove this complex text code please. It's substantially more complex than the compiler code and hard to understand, so I don't think it will help us be more efficient with future modifications to this code.

File: compiler-cli/src/new.rs [hunk 2]
```diff
@@ -461,3 +473,52 @@ fn get_foldername(path: &str) -> Result<String, Error> {
             }),
     }
 }
+
+fn derive_initial_project_name(name: Option<&String>, project_root: &str) -> Result<String, Error> {
```
Comment (lpil) [inline compiler-cli/src/new.rs]: This work is now performed twice! Inline this code again and instead return both the needed values.

File: compiler-cli/src/new.rs [hunk 3]
```diff
@@ -204,7 +207,15 @@ jobs:
...
 impl Creator {
     fn new(options: NewOptions, gleam_version: &'static str) -> Result<Self, Error> {
+        let mut options = options;
+
+        // Record the folder-derived starting name so we can detect later renames prompted to the user.
+        let initial_name =
+            derive_initial_project_name(options.name.as_ref(), &options.project_root)?;
         let project_name = get_valid_project_name(options.name.clone(), &options.project_root)?;
+
+        align_project_root_with_project_name(&mut options, &initial_name, &project_name);
```
Comment (lpil) [inline compiler-cli/src/new.rs]: It's hard to know what this function does because it has this mutation based API. Rewrite it in the functional style for clarity, with functions taking arguments and returning values.

File: compiler-cli/src/new/tests.rs [hunk 4]
```diff
@@ -337,6 +337,38 @@ fn skip_existing_git_files_when_skip_git_is_true() {
     assert!(path.join(".gitignore").exists());
 }
 
+#[test]
+fn suggested_project_name_updates_directory() {
```
Comment (lpil) [inline compiler-cli/src/new/tests.rs:341]: Very nice, thank you

**Review by lpil — APPROVED** [review]
Thank you! Really great quality of the code you've been submitting too, great work!
