### PR TITLE
Fix go to definition for unqualified functions

### LINKED ISSUE #3457: LSP: Goto Definition not working properly for unqualified imports
The LSP action "Goto Definition" (`gd` in nvim) is not working for unqualified imported functions.
With the following example of (part of) a file (from the [Building your first Gleam web app with Wisp and Lustre](https://gleaming.dev/articles/building-your-first-gleam-web-app/) tutorial),

```gleam
import app/routes/item_routes.{items_middleware}
import app/web.{type Context}
import wisp.{type Request, type Response}

pub fn handle_request(req: Request, ctx: Context) -> Response {
  use req <- web.middleware(req, ctx)
  use ctx <- items_middleware(req, ctx)
// ...
```

the following behaviors are observed:
* Placing the cursor on `items_middleware` and hitting `gd` moves the cursor to the `req` symbol on the same line.
* Placing the cursor on `web.middleware` (specifically on the `.middleware` part) and hitting `gd` correctly jumps to that function's definition in `app/web`.
* Placing the cursor on any of the imported types (`Context` or `Request`) and hitting `gd` correctly jumps to their definition.

Gleam v1.3.2 running on WSL (Ubuntu 22.04.4 LTS)
Neovim v0.11.0-dev

### PR DESCRIPTION
**Pull request by GearsDatapacks**
Fixes #3457
Very simple fix, functions just weren't returning their module in `definition_location`.

### CODE REVIEW

File: compiler-core/src/language_server/engine.rs [hunk 1]
```diff
@@ -174,13 +174,17 @@ where
...
+            eprintln!("{node:#?}");
+
             let location = match node
                 .definition_location(this.compiler.project_compiler.get_importable_modules())
             {
                 Some(location) => location,
                 None => return Ok(None),
             };
 
+            eprintln!("{location:#?}");
```
Comment (lpil) [inline compiler-core/src/language_server/engine.rs:186]: There's two debug statements left in here

**Review by lpil — COMMENTED** [review]
Nice! Thank you!! One small note inline

**Comment by GearsDatapacks** [comment]
Oops, fixed!

**Review by lpil — APPROVED** [review]
Thank you
