### PR TITLE
Bugfix: path dependencies module resolution bug with local paths

### LINKED ISSUE #2278: Path dependencies module resolution bug
## Description of behaviour

Given some project `foo` that has a path dependency `bar`, if `bar` adds a dependency `baz` **after** `foo` has already been built, attempting to rebuild `foo` will fail complaining that module `baz` cannot be found.

## Steps to reproduce

[The following steps but as a video](https://youtu.be/EZVfqzb8bF4)

Given the following project setup:

```
foo/
  gleam.toml
  src/
    foo.gleam
bar/
  gleam.toml
  src/
    bar.gleam
```

```toml
# foo/gleam.toml 

[dependencies]
bar = { path = "../bar" }
```

```gleam
// foo/src/foo.gleam

import bar

pub fn main() {
  bar.say_hello()
}
```

```toml
# bar/gleam.toml

[dependencies]
gleam_stdlib = "~> 0.29"
```

```gleam
// bar/src/bar.gleam

import gleam/io

pub fn say_hello() {
  io.println("Hello from bar!")
}
```

If you then take the following commands:

```sh
~/foo $ gleam build
~/foo $ cd ../bar
~/bar $ gleam add simplifile
```

And then update `bar/src/bar.gleam` like following

```gleam
// bar/src/bar.gleam

import simplifile
import gleam/io

pub fn say_hello() {
  let assert Ok(_) = simplifile.make_directory("hello-from-bar")

  io.println("Hello from bar!")
}
```

And then finally attempt to build foo again

```sh
~/foo $ gleam build
```

It will fail with the following error message:

```
  Compiling gleam_stdlib
  Compiling bar
error: Unknown module
  ┌─ /Users/dan/Repositories/gleam-path-deps-bug/bar/src/bar.gleam:1:8
  │
1 │ import simplifile
  │        ^^^^^^^^^^

No module has been found with the name `simplifile`.
```

### PR DESCRIPTION
**Pull request by daniellionel01**
Code to fix https://github.com/gleam-lang/gleam/issues/2278

I hope this is an acceptable solution, I've inspected closed PRs that didn't make it attempting to fix this issue (https://github.com/gleam-lang/gleam/pull/2334 and https://github.com/gleam-lang/gleam/pull/3398).

In summary this approach stores a hash of the manifest.toml of all dependencies that are a path dependencies in the build directory and rebuilds any packages if the manifest.toml should change.

Let me know if I've missed anything or if this approach does not scale well, thank you!

Also I did not want to clutter the codebase with it, but here is a script (thank you GPT) to test the scenario that produces the error mentioned in the linked issue. It assumes you're running it in the root of the gleam codebase, otherwise you can adjust the `GLEAM_BIN` path. Also this script probably only works on a mac or linux. Here is the script:

```bash
#!/bin/bash
set -e

# Use the locally built gleam executable
GLEAM_BIN="$PWD/target/debug/gleam"

# Ensure the local build exists
if [ ! -f "$GLEAM_BIN" ]; then
    echo "Error: Local Gleam build not found at $GLEAM_BIN"
    echo "Please run 'cargo build' first"
    exit 1
fi

echo "Using Gleam binary at: $GLEAM_BIN"

# Create a temporary directory for the test
TEST_DIR=$(mktemp -d)
echo "Creating test environment in $TEST_DIR"

# Create bar (dependency) project
echo "Creating bar project (the dependency)"
cd $TEST_DIR
mkdir -p bar
cd bar

# Initialize bar project
cat > gleam.toml << EOF
name = "bar"
version = "0.1.0"

[dependencies]
gleam_stdlib = "~> 0.29"
EOF

# Create bar module
mkdir -p src
cat > src/bar.gleam << EOF
import gleam/io

pub fn say_hello() {
  io.println("Hello from bar!")
}
EOF

# Create foo (root) project
echo "Creating foo project (the root project)"
cd $TEST_DIR
mkdir -p foo
cd foo

# Initialize foo project with bar as path dependency
cat > gleam.toml << EOF
name = "foo"
version = "0.1.0"

[dependencies]
bar = { path = "../bar" }
EOF

# Create foo module that imports bar
mkdir -p src
cat > src/foo.gleam << EOF
import bar

pub fn main() {
  bar.say_hello()
}
EOF

# First build of foo
echo "Building foo for the first time..."
cd $TEST_DIR/foo
$GLEAM_BIN build

# Add simplifile dependency to bar
echo "Adding simplifile dependency to bar..."
cd $TEST_DIR/bar
$GLEAM_BIN add simplifile

# Update bar module to use simplifile
cat > src/bar.gleam << EOF
import simplifile
import gleam/io

pub fn say_hello() {
  io.println("Hello from bar!")
}
EOF

# Build foo again - this should now succeed with our fix
echo "Building foo again after adding simplifile to bar..."
cd $TEST_DIR/foo
$GLEAM_BIN build

if [ $? -eq 0 ]; then
  echo -e "\n\033[0;32mSUCCESS: The fix works! Foo successfully built after bar added simplifile dependency.\033[0m"
else
  echo -e "\n\033[0;31mFAILURE: The fix didn't work. Foo failed to build after bar added simplifile dependency.\033[0m"
  exit 1
fi

# Clean up
echo -e "\nTest directory: $TEST_DIR"
echo "You can safely remove this directory when done with: rm -rf $TEST_DIR"
echo "Or inspect it to see the project structure."
```

### CODE REVIEW

File: compiler-cli/src/dependencies.rs [hunk 1]
```diff
@@ -672,6 +672,66 @@ fn is_same_requirements(
         }
     }
 
+    // For path dependencies, we need to check if their manifest.toml files have changed,
+    // which indicates that their dependencies have changed
+    for (key, requirement2) in requirements2 {
+        if let Requirement::Path { path } = requirement2 {
+            let dep_manifest_path = root_path.join(path).join("manifest.toml");
```
Comment (lpil) [inline compiler-cli/src/dependencies.rs]: All path manipulation must be done in the ProjectPaths class, no other code is permitted to use `.join` etc.

File: compiler-cli/src/dependencies.rs [hunk 2]
```diff
@@ -888,6 +948,11 @@ fn provide_local_package(
     } else {
         fs::canonicalise(&parent_path.join(package_path))?
     };
+
+    // We used to always force clean artifacts for path dependencies,
+    // but now we use the gleam.toml hash tracking in is_same_requirements
+    // to determine when path dependency dependencies have changed
```
Comment (lpil) [inline compiler-cli/src/dependencies.rs]: What does this comment mean?

File: compiler-cli/src/dependencies.rs [hunk 3]
```diff
@@ -672,6 +672,66 @@ fn is_same_requirements(
         }
     }
 
+    // For path dependencies, we need to check if their manifest.toml files have changed,
+    // which indicates that their dependencies have changed
+    for (key, requirement2) in requirements2 {
```
Comment (lpil) [inline compiler-cli/src/dependencies.rs]: This equality checking logic should be in the `same_requirements` function as that's the one that checks equality, while this one iterates over the collection.

File: compiler-cli/src/dependencies.rs [hunk 4]
```diff
@@ -672,6 +672,66 @@ fn is_same_requirements(
...
+
+            let manifest_content = match fs::read(&dep_manifest_path) {
+                Ok(content) => content,
+                Err(_) => {
+                    tracing::debug!("cannot_read_path_dependency_manifest_forcing_rebuild");
+                    return Ok(false);
+                }
+            };
+
+            let mut hasher = std::hash::DefaultHasher::new();
```
Comment (lpil) [inline compiler-cli/src/dependencies.rs]: We use `xxhash_rust::xxh3::xxh3_64` for fingerprinting, not the default hasher.

File: compiler-cli/src/dependencies.rs [hunk 5]
```diff
@@ -672,6 +672,66 @@ fn is_same_requirements(
...
+                return Ok(false);
+            }
+
+            let manifest_content = match fs::read(&dep_manifest_path) {
+                Ok(content) => content,
+                Err(_) => {
+                    tracing::debug!("cannot_read_path_dependency_manifest_forcing_rebuild");
+                    return Ok(false);
+                }
+            };
```
Comment (lpil) [inline compiler-cli/src/dependencies.rs]: We check mtimes before we hash, to avoid extra work, so let's add that here.

File: compiler-cli/src/dependencies.rs [hunk 6]
```diff
@@ -672,6 +672,66 @@ fn is_same_requirements(
...
+
+            let mut hasher = std::hash::DefaultHasher::new();
+            std::hash::Hash::hash(&manifest_content, &mut hasher);
+            let current_hash = std::hash::Hasher::finish(&hasher).to_string();
+
+            // If cached hash file doesn't exist, this is the first time we're checking this dependency
+            if !cached_hash_path.exists() {
+                // Save the current hash for future comparisons
+                if let Err(e) = fs::write(&cached_hash_path, &current_hash) {
```
Comment (lpil) [inline compiler-cli/src/dependencies.rs]: The errors in this code are being silently discarded! They must always be passed back up.

File: compiler-cli/src/dependencies.rs [hunk 7]
```diff
@@ -672,6 +672,66 @@ fn is_same_requirements(
...
+            // Check if we have a cached hash for this path dependency's manifest.toml
+            // Use the dependency name instead of the path for the manifest hash file
+            let cached_hash_path = root_path
+                .join("build")
+                .join("packages")
+                .join(format!("{}.manifest_hash", key));
+
+            if !dep_manifest_path.exists() {
+                tracing::debug!("path_dependency_manifest_not_found_forcing_rebuild");
+                return Ok(false);
```
Comment (lpil) [inline compiler-cli/src/dependencies.rs]: This would result in rebuilding every single time when there's no manifest for the path dep!

File: compiler-cli/src/dependencies.rs [hunk 8]
```diff
@@ -672,6 +672,66 @@ fn is_same_requirements(
         }
     }
 
+    // For path dependencies, we need to check if their manifest.toml files have changed,
```
Comment (lpil) [inline compiler-cli/src/dependencies.rs]: The name for this function doesn't fit what it does any more- even if the requirements are the same the function can return false in the instance that the definition of one of the required deps has changed.

The functions have also been made effectful and to depend on file system state, so that would need to be communicated clearly in the name and arguments too.

These functions that check the requirements are the same could go unchanged (which would still fit the "is same requirements" name) and a new function could be created to check just the path deps have not changed their deps.

**Review by lpil — COMMENTED** [review]
Sorry this took so long for me to review! I missed it somehow, and I've only just seen it now.

Thank you for this, I've left some comments inline. Tests will need to be added too.

File: compiler-cli/src/dependencies.rs (hunk 2 above)
Comment (daniellionel01) [reply compiler-cli/src/dependencies.rs]: caught my GPT generated snippet. Sorry, removing it.

File: compiler-cli/src/dependencies.rs (hunk 3 above)
Comment (daniellionel01) [reply compiler-cli/src/dependencies.rs]: yeah, I removed the comment

File: compiler-cli/src/dependencies.rs (hunk 4 above)
Comment (daniellionel01) [reply compiler-cli/src/dependencies.rs]: Done!

File: compiler-cli/src/dependencies.rs (hunk 5 above)
Comment (daniellionel01) [reply compiler-cli/src/dependencies.rs]: Done!

File: compiler-cli/src/dependencies.rs (hunk 6 above)
Comment (daniellionel01) [reply compiler-cli/src/dependencies.rs]: Done!

File: compiler-cli/src/dependencies.rs (hunk 7 above)
Comment (daniellionel01) [reply compiler-cli/src/dependencies.rs]: Sorry! `continue`-ing instead now

File: compiler-cli/src/dependencies.rs (hunk 1 above)
Comment (daniellionel01) [reply compiler-cli/src/dependencies.rs]: Done!

File: compiler-cli/src/dependencies.rs (hunk 8 above)
Comment (daniellionel01) [reply compiler-cli/src/dependencies.rs]: pushed an update!

**Comment by daniellionel01** [comment]
@lpil Addressed all comments!

Also added tests, that you can checkout.

Thank you for the input!

**Comment by giacomocavalieri** [comment]
Hello! If this is ready please remember to un-draft it, also would you mind rebasing on main? It seems there's some conflicts

**Comment by daniellionel01** [comment]
> Hello! If this is ready please remember to un-draft it, also would you mind rebasing on main? It seems there's some conflicts

i'll get on rebasing!

**Comment by daniellionel01** [comment]
@lpil @giacomocavalieri ready to merge from my end!

**Review by giacomocavalieri — APPROVED** [review]

**Review by lpil — APPROVED** [review]
Thank you!!!
