### PR TITLE
Switch from Cap'n'proto to Serde for cache

### LINKED ISSUE #1599: Switch from capnproto to serde
Switch from capnproto to serde with https://github.com/bincode-org/bincode, this is because capnproto is difficult to work with while serde is not. Capnproto is also very time-consuming to work with and is error prone.

### LINKED ISSUE #5260: Metadata decoder error: "Message is too deeply-nested" when using deeply nested constants
When defining a deeply nested data structure (in this case, a Huffman tree for HPACK) as a constant, the Gleam compiler fails when attempting to decode the metadata. Moving the exact same structure into a function resolves the issue.

## Steps to reproduce:
1. Create a module with deeply nested constant:
```gleam
pub type TreeNode {
  Leaf(Int)
  Branch(zero: TreeNode, one: TreeNode)
  Empty
}

pub const tree = Branch(
  Branch(
    Branch(
      Branch(Branch(Leaf(48), Leaf(49)), Branch(Leaf(50), Leaf(97))),
      Branch(Branch(Leaf(99), Leaf(101)), Branch(Leaf(105), Leaf(111))),
    ),
    Branch(
      Branch(
        Branch(Leaf(115), Leaf(116)),
        Branch(Branch(Leaf(32), Leaf(37)), Branch(Leaf(45), Leaf(46))),
      ),
      Branch(
        Branch(Branch(Leaf(47), Leaf(51)), Branch(Leaf(52), Leaf(53))),
        Branch(Branch(Leaf(54), Leaf(55)), Branch(Leaf(56), Leaf(57))),
      ),
    ),
  ),
  Branch(
    Branch(
      Branch(
        Branch(Branch(Leaf(61), Leaf(65)), Branch(Leaf(95), Leaf(98))),
        Branch(Branch(Leaf(100), Leaf(102)), Branch(Leaf(103), Leaf(104))),
      ),
      Branch(
        Branch(Branch(Leaf(108), Leaf(109)), Branch(Leaf(110), Leaf(112))),
        Branch(
          Branch(Leaf(114), Leaf(117)),
          Branch(Branch(Leaf(58), Leaf(66)), Branch(Leaf(67), Leaf(68))),
        ),
      ),
    ),
    Branch(
      Branch(
        Branch(
          Branch(Branch(Leaf(69), Leaf(70)), Branch(Leaf(71), Leaf(72))),
          Branch(Branch(Leaf(73), Leaf(74)), Branch(Leaf(75), Leaf(76))),
        ),
        Branch(
          Branch(Branch(Leaf(77), Leaf(78)), Branch(Leaf(79), Leaf(80))),
          Branch(Branch(Leaf(81), Leaf(82)), Branch(Leaf(83), Leaf(84))),
        ),
      ),
      Branch(
        Branch(
          Branch(Branch(Leaf(85), Leaf(86)), Branch(Leaf(87), Leaf(89))),
          Branch(Branch(Leaf(106), Leaf(107)), Branch(Leaf(113), Leaf(118))),
        ),
        Branch(
          Branch(Branch(Leaf(119), Leaf(120)), Branch(Leaf(121), Leaf(122))),
          Branch(
            Branch(Branch(Leaf(38), Leaf(42)), Branch(Leaf(44), Leaf(59))),
            Branch(
              Branch(Leaf(88), Leaf(90)),
              Branch(
                Branch(Branch(Leaf(33), Leaf(34)), Branch(Leaf(40), Leaf(41))),
                Branch(
                  Branch(Leaf(63), Branch(Leaf(39), Leaf(43))),
                  Branch(
                    Branch(Leaf(124), Branch(Leaf(35), Leaf(62))),
                    Branch(
                      Branch(
                        Branch(Leaf(0), Leaf(36)),
                        Branch(Leaf(64), Leaf(91)),
                      ),
                      Branch(
                        Branch(Leaf(93), Leaf(126)),
                        Branch(
                          Branch(Leaf(94), Leaf(125)),
                          Branch(
                            Branch(Leaf(60), Leaf(96)),
                            Branch(
                              Leaf(123),
                              Branch(
                                Branch(
                                  Branch(
                                    Branch(Leaf(92), Leaf(195)),
                                    Branch(
                                      Leaf(208),
                                      Branch(Leaf(128), Leaf(130)),
                                    ),
                                  ),
                                  Branch(
                                    Branch(
                                      Branch(Leaf(131), Leaf(162)),
                                      Branch(Leaf(184), Leaf(194)),
                                    ),
                                    Branch(
                                      Branch(Leaf(224), Leaf(226)),
                                      Branch(
                                        Branch(Leaf(153), Leaf(161)),
                                        Branch(Leaf(167), Leaf(172)),
                                      ),
                                    ),
                                  ),
                                ),
                                Branch(
                                  Branch(
                                    Branch(
                                      Branch(
                                        Branch(Leaf(176), Leaf(177)),
                                        Branch(Leaf(179), Leaf(209)),
                                      ),
                                      Branch(
                                        Branch(Leaf(216), Leaf(217)),
                                        Branch(Leaf(227), Leaf(229)),
                                      ),
                                    ),
                                    Branch(
                                      Branch(
                                        Branch(
                                          Leaf(230),
                                          Branch(Leaf(129), Leaf(132)),
                                        ),
                                        Branch(
                                          Branch(Leaf(133), Leaf(134)),
                                          Branch(Leaf(136), Leaf(146)),
                                        ),
                                      ),
                                      Branch(
                                        Branch(
                                          Branch(Leaf(154), Leaf(156)),
                                          Branch(Leaf(160), Leaf(163)),
                                        ),
                                        Branch(
                                          Branch(Leaf(164), Leaf(169)),
                                          Branch(Leaf(170), Leaf(173)),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Branch(
                                    Branch(
                                      Branch(
                                        Branch(
                                          Branch(Leaf(178), Leaf(181)),
                                          Branch(Leaf(185), Leaf(186)),
                                        ),
                                        Branch(
                                          Branch(Leaf(187), Leaf(189)),
                                          Branch(Leaf(190), Leaf(196)),
                                        ),
                                      ),
                                      Branch(
                                        Branch(
                                          Branch(Leaf(198), Leaf(228)),
                                          Branch(Leaf(232), Leaf(233)),
                                        ),
                                        Branch(
                                          Branch(
                                            Branch(Leaf(1), Leaf(135)),
                                            Branch(Leaf(137), Leaf(138)),
                                          ),
                                          Branch(
                                            Branch(Leaf(139), Leaf(140)),
                                            Branch(Leaf(141), Leaf(143)),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Branch(
                                      Branch(
                                        Branch(
                                          Branch(
                                            Branch(Leaf(147), Leaf(149)),
                                            Branch(Leaf(150), Leaf(151)),
                                          ),
                                          Branch(
                                            Branch(Leaf(152), Leaf(155)),
                                            Branch(Leaf(157), Leaf(158)),
                                          ),
                                        ),
                                        Branch(
                                          Branch(
                                            Branch(Leaf(165), Leaf(166)),
                                            Branch(Leaf(168), Leaf(174)),
                                          ),
                                          Branch(
                                            Branch(Leaf(175), Leaf(180)),
                                            Branch(Leaf(182), Leaf(183)),
                                          ),
                                        ),
                                      ),
                                      Branch(
                                        Branch(
                                          Branch(
                                            Branch(Leaf(188), Leaf(191)),
                                            Branch(Leaf(197), Leaf(231)),
                                          ),
                                          Branch(
                                            Branch(
                                              Leaf(239),
                                              Branch(Leaf(9), Leaf(142)),
                                            ),
                                            Branch(
                                              Branch(Leaf(144), Leaf(145)),
                                              Branch(Leaf(148), Leaf(159)),
                                            ),
                                          ),
                                        ),
                                        Branch(
                                          Branch(
                                            Branch(
                                              Branch(Leaf(171), Leaf(206)),
                                              Branch(Leaf(215), Leaf(225)),
                                            ),
                                            Branch(
                                              Branch(Leaf(236), Leaf(237)),
                                              Branch(
                                                Branch(Leaf(199), Leaf(207)),
                                                Branch(Leaf(234), Leaf(235)),
                                              ),
                                            ),
                                          ),
                                          Branch(
                                            Branch(
                                              Branch(
                                                Branch(
                                                  Branch(Leaf(192), Leaf(193)),
                                                  Branch(Leaf(200), Leaf(201)),
                                                ),
                                                Branch(
                                                  Branch(Leaf(202), Leaf(205)),
                                                  Branch(Leaf(210), Leaf(213)),
                                                ),
                                              ),
                                              Branch(
                                                Branch(
                                                  Branch(Leaf(218), Leaf(219)),
                                                  Branch(Leaf(238), Leaf(240)),
                                                ),
                                                Branch(
                                                  Branch(Leaf(242), Leaf(243)),
                                                  Branch(
                                                    Leaf(255),
                                                    Branch(Leaf(203), Leaf(204)),
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Branch(
                                              Branch(
                                                Branch(
                                                  Branch(
                                                    Branch(Leaf(211), Leaf(212)),
                                                    Branch(Leaf(214), Leaf(221)),
                                                  ),
                                                  Branch(
                                                    Branch(Leaf(222), Leaf(223)),
                                                    Branch(Leaf(241), Leaf(244)),
                                                  ),
                                                ),
                                                Branch(
                                                  Branch(
                                                    Branch(Leaf(245), Leaf(246)),
                                                    Branch(Leaf(247), Leaf(248)),
                                                  ),
                                                  Branch(
                                                    Branch(Leaf(250), Leaf(251)),
                                                    Branch(Leaf(252), Leaf(253)),
                                                  ),
                                                ),
                                              ),
                                              Branch(
                                                Branch(
                                                  Branch(
                                                    Branch(
                                                      Leaf(254),
                                                      Branch(Leaf(2), Leaf(3)),
                                                    ),
                                                    Branch(
                                                      Branch(Leaf(4), Leaf(5)),
                                                      Branch(Leaf(6), Leaf(7)),
                                                    ),
                                                  ),
                                                  Branch(
                                                    Branch(
                                                      Branch(Leaf(8), Leaf(11)),
                                                      Branch(Leaf(12), Leaf(14)),
                                                    ),
                                                    Branch(
                                                      Branch(Leaf(15), Leaf(16)),
                                                      Branch(Leaf(17), Leaf(18)),
                                                    ),
                                                  ),
                                                ),
                                                Branch(
                                                  Branch(
                                                    Branch(
                                                      Branch(Leaf(19), Leaf(20)),
                                                      Branch(Leaf(21), Leaf(23)),
                                                    ),
                                                    Branch(
                                                      Branch(Leaf(24), Leaf(25)),
                                                      Branch(Leaf(26), Leaf(27)),
                                                    ),
                                                  ),
                                                  Branch(
                                                    Branch(
                                                      Branch(Leaf(28), Leaf(29)),
                                                      Branch(Leaf(30), Leaf(31)),
                                                    ),
                                                    Branch(
                                                      Branch(
                                                        Leaf(127),
                                                        Leaf(220),
                                                      ),
                                                      Branch(
                                                        Leaf(249),
                                                        Branch(
                                                          Branch(
                                                            Leaf(10),
                                                            Leaf(13),
                                                          ),
                                                          Branch(
                                                            Leaf(22),
                                                            Empty,
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  ),
)
```
2. Attempt to compile the project or import this module into another module.
3. The compiler returns the following error:
>A problem was encountered when decoding the metadata for one of the Gleam dependency modules.
>The error from the decoder library was:
>Message is too deeply-nested or contains cycles.
4. Change pub const huffman_tree = ... to pub fn huffman_tree() { ... }. The error disappears

## Versions:
- Gleam: v1.14.0
- OS: Arch linux
- Runtime: Erlang/OTP 28

## Logs:
```bash
DEBUG download_deps: locking_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam.lock"
TRACE download_deps: reading_file path="/home/wiskiy/dev/gleamy/server/gleam.toml"
DEBUG download_deps: reading_manifest_toml
TRACE download_deps: reading_file path="/home/wiskiy/dev/gleamy/server/manifest.toml"
TRACE download_deps: reading_file path="/home/wiskiy/dev/gleamy/server/build/packages/packages.toml"
DEBUG download_deps: locking_directory path="/home/wiskiy/dev/gleamy/server/build/gleam-dev-erlang.lock"
DEBUG download_deps: locking_directory path="/home/wiskiy/dev/gleamy/server/build/gleam-dev-javascript.lock"
DEBUG download_deps: locking_directory path="/home/wiskiy/dev/gleamy/server/build/gleam-prod-erlang.lock"
DEBUG download_deps: locking_directory path="/home/wiskiy/dev/gleamy/server/build/gleam-prod-javascript.lock"
DEBUG download_deps: locking_directory path="/home/wiskiy/dev/gleamy/server/build/gleam-lsp-erlang.lock"
DEBUG download_deps: locking_directory path="/home/wiskiy/dev/gleamy/server/build/gleam-lsp-javascript.lock"
TRACE download_deps: writing_file path="/home/wiskiy/dev/gleamy/server/build/packages/packages.toml"
TRACE reading_file path="/home/wiskiy/dev/gleamy/server/gleam.toml"
 INFO Compiling packages
DEBUG locking_directory path="/home/wiskiy/dev/gleamy/server/build/gleam-dev-erlang.lock"
TRACE reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_version"
TRACE reading_file path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/gleam.toml"
TRACE compile{package=gleam_stdlib}:load: gleam_source_files "/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src"
TRACE compile{package=gleam_stdlib}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src"
TRACE compile{package=gleam_stdlib}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@bool.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@bytes_tree.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@dict.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@list.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@io.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@int.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@pair.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@bit_array.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@option.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@function.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@uri.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@float.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@string_tree.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam/dynamic"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@set.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@result.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@order.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@string.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@dynamic.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@dynamic@decode.cache_meta"
TRACE compile{package=gleam_stdlib}: CacheFiles::modules_with_meta_files "/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts"
TRACE compile{package=gleam_stdlib}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/order
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@order.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@order.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/float
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@float.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@float.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/int
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@int.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@int.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/option
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@option.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@option.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/dict
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@dict.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@dict.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/list
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@list.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@list.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/string_tree
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@string_tree.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@string_tree.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/string
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@string.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@string.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/bit_array
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@bit_array.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@bit_array.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/bool
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@bool.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@bool.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/bytes_tree
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@bytes_tree.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@bytes_tree.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/dynamic
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@dynamic.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@dynamic.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/dynamic/decode
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@dynamic@decode.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@dynamic@decode.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/function
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@function.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@function.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/io
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@io.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@io.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/pair
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@pair.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@pair.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/result
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@result.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@result.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/set
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@set.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@set.cache_inline"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/uri
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@uri.cache"
TRACE compile{package=gleam_stdlib}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@uri.cache_inline"
 INFO compile{package=gleam_stdlib}: analysing_modules count=0
DEBUG compile{package=gleam_stdlib}: performing_code_generation
DEBUG compile{package=gleam_stdlib}: copying_native_source_files
TRACE compile{package=gleam_stdlib}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src"
TRACE compile{package=gleam_stdlib}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@pair.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@set.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@list.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@function.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@bit_array.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@option.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@string_tree.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@order.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam_stdlib.mjs"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@bytes_tree.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam_stdlib.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@dynamic.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/dict.mjs"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@int.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@uri.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@result.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@io.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@string.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@dict.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@dynamic@decode.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@float.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam@bool.erl"
TRACE compile{package=gleam_stdlib}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_stdlib/src/gleam/dynamic"
DEBUG compile{package=gleam_stdlib}: skipping_entrypoint_generation
DEBUG compile{package=gleam_stdlib}: no_erlang_to_compile
TRACE compile{package=gleam_stdlib}: writing_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_stdlib/ebin/gleam_stdlib.app"
TRACE reading_file path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/gleam.toml"
TRACE compile{package=gleam_erlang}:load: gleam_source_files "/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src"
TRACE compile{package=gleam_erlang}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src"
TRACE compile{package=gleam_erlang}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam"
TRACE compile{package=gleam_erlang}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam/erlang"
TRACE compile{package=gleam_erlang}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@charlist.cache_meta"
TRACE compile{package=gleam_erlang}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@process.cache_meta"
TRACE compile{package=gleam_erlang}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@application.cache_meta"
TRACE compile{package=gleam_erlang}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@reference.cache_meta"
TRACE compile{package=gleam_erlang}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@port.cache_meta"
TRACE compile{package=gleam_erlang}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@node.cache_meta"
TRACE compile{package=gleam_erlang}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@atom.cache_meta"
TRACE compile{package=gleam_erlang}: CacheFiles::modules_with_meta_files "/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts"
TRACE compile{package=gleam_erlang}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts"
DEBUG compile{package=gleam_erlang}: module_to_load_from_cache module=gleam/erlang/atom
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@atom.cache"
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@atom.cache_inline"
DEBUG compile{package=gleam_erlang}: module_to_load_from_cache module=gleam/erlang/node
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@node.cache"
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@node.cache_inline"
DEBUG compile{package=gleam_erlang}: module_to_load_from_cache module=gleam/erlang/application
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@application.cache"
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@application.cache_inline"
DEBUG compile{package=gleam_erlang}: module_to_load_from_cache module=gleam/erlang/charlist
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@charlist.cache"
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@charlist.cache_inline"
DEBUG compile{package=gleam_erlang}: module_to_load_from_cache module=gleam/erlang/port
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@port.cache"
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@port.cache_inline"
DEBUG compile{package=gleam_erlang}: module_to_load_from_cache module=gleam/erlang/reference
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@reference.cache"
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@reference.cache_inline"
DEBUG compile{package=gleam_erlang}: module_to_load_from_cache module=gleam/erlang/process
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@process.cache"
TRACE compile{package=gleam_erlang}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@process.cache_inline"
 INFO compile{package=gleam_erlang}: analysing_modules count=0
DEBUG compile{package=gleam_erlang}: performing_code_generation
DEBUG compile{package=gleam_erlang}: copying_native_source_files
TRACE compile{package=gleam_erlang}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src"
TRACE compile{package=gleam_erlang}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam"
DEBUG compile{package=gleam_erlang}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam@erlang@charlist.erl"
DEBUG compile{package=gleam_erlang}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam@erlang@process.erl"
DEBUG compile{package=gleam_erlang}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam@erlang@port.erl"
DEBUG compile{package=gleam_erlang}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam@erlang@atom.erl"
DEBUG compile{package=gleam_erlang}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam@erlang@application.erl"
DEBUG compile{package=gleam_erlang}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam_erlang_ffi.erl"
DEBUG compile{package=gleam_erlang}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam@erlang@node.erl"
DEBUG compile{package=gleam_erlang}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam@erlang@reference.erl"
TRACE compile{package=gleam_erlang}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_erlang/src/gleam/erlang"
DEBUG compile{package=gleam_erlang}: skipping_entrypoint_generation
DEBUG compile{package=gleam_erlang}: no_erlang_to_compile
TRACE compile{package=gleam_erlang}: writing_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_erlang/ebin/gleam_erlang.app"
TRACE reading_file path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/gleam.toml"
TRACE compile{package=gleam_otp}:load: gleam_source_files "/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src"
TRACE compile{package=gleam_otp}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src"
TRACE compile{package=gleam_otp}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam"
TRACE compile{package=gleam_otp}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam/otp"
TRACE compile{package=gleam_otp}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@static_supervisor.cache_meta"
TRACE compile{package=gleam_otp}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@factory_supervisor.cache_meta"
TRACE compile{package=gleam_otp}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@system.cache_meta"
TRACE compile{package=gleam_otp}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@actor.cache_meta"
TRACE compile{package=gleam_otp}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@supervision.cache_meta"
TRACE compile{package=gleam_otp}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam/otp/internal"
TRACE compile{package=gleam_otp}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@port.cache_meta"
TRACE compile{package=gleam_otp}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@internal@result2.cache_meta"
TRACE compile{package=gleam_otp}: CacheFiles::modules_with_meta_files "/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts"
TRACE compile{package=gleam_otp}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts"
DEBUG compile{package=gleam_otp}: module_to_load_from_cache module=gleam/otp/system
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@system.cache"
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@system.cache_inline"
DEBUG compile{package=gleam_otp}: module_to_load_from_cache module=gleam/otp/actor
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@actor.cache"
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@actor.cache_inline"
DEBUG compile{package=gleam_otp}: module_to_load_from_cache module=gleam/otp/internal/result2
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@internal@result2.cache"
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@internal@result2.cache_inline"
DEBUG compile{package=gleam_otp}: module_to_load_from_cache module=gleam/otp/supervision
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@supervision.cache"
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@supervision.cache_inline"
DEBUG compile{package=gleam_otp}: module_to_load_from_cache module=gleam/otp/factory_supervisor
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@factory_supervisor.cache"
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@factory_supervisor.cache_inline"
DEBUG compile{package=gleam_otp}: module_to_load_from_cache module=gleam/otp/port
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@port.cache"
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@port.cache_inline"
DEBUG compile{package=gleam_otp}: module_to_load_from_cache module=gleam/otp/static_supervisor
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@static_supervisor.cache"
TRACE compile{package=gleam_otp}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@static_supervisor.cache_inline"
 INFO compile{package=gleam_otp}: analysing_modules count=0
DEBUG compile{package=gleam_otp}: performing_code_generation
DEBUG compile{package=gleam_otp}: copying_native_source_files
TRACE compile{package=gleam_otp}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src"
TRACE compile{package=gleam_otp}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam"
DEBUG compile{package=gleam_otp}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam@otp@factory_supervisor.erl"
DEBUG compile{package=gleam_otp}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam@otp@internal@result2.erl"
DEBUG compile{package=gleam_otp}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam_otp_external.erl"
DEBUG compile{package=gleam_otp}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam@otp@supervision.erl"
DEBUG compile{package=gleam_otp}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam@otp@port.erl"
DEBUG compile{package=gleam_otp}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam@otp@system.erl"
DEBUG compile{package=gleam_otp}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam@otp@static_supervisor.erl"
DEBUG compile{package=gleam_otp}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam@otp@actor.erl"
TRACE compile{package=gleam_otp}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam/otp"
TRACE compile{package=gleam_otp}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleam_otp/src/gleam/otp/internal"
DEBUG compile{package=gleam_otp}: skipping_entrypoint_generation
DEBUG compile{package=gleam_otp}: no_erlang_to_compile
TRACE compile{package=gleam_otp}: writing_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleam_otp/ebin/gleam_otp.app"
TRACE reading_file path="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/gleam.toml"
TRACE compile{package=gleeunit}:load: gleam_source_files "/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src"
TRACE compile{package=gleeunit}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src"
TRACE compile{package=gleeunit}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit.cache_meta"
TRACE compile{package=gleeunit}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit"
TRACE compile{package=gleeunit}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit/internal"
TRACE compile{package=gleeunit}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit@should.cache_meta"
TRACE compile{package=gleeunit}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit@internal@gleam_panic.cache_meta"
TRACE compile{package=gleeunit}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit@internal@reporting.cache_meta"
TRACE compile{package=gleeunit}: CacheFiles::modules_with_meta_files "/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts"
TRACE compile{package=gleeunit}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts"
TRACE compile{package=gleeunit}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit"
TRACE compile{package=gleeunit}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit/internal"
DEBUG compile{package=gleeunit}: module_to_load_from_cache module=gleeunit
TRACE compile{package=gleeunit}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit.cache"
TRACE compile{package=gleeunit}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit.cache_inline"
DEBUG compile{package=gleeunit}: module_to_load_from_cache module=gleeunit/internal/gleam_panic
TRACE compile{package=gleeunit}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit@internal@gleam_panic.cache"
TRACE compile{package=gleeunit}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit@internal@gleam_panic.cache_inline"
DEBUG compile{package=gleeunit}: module_to_load_from_cache module=gleeunit/internal/reporting
TRACE compile{package=gleeunit}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit@internal@reporting.cache"
TRACE compile{package=gleeunit}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit@internal@reporting.cache_inline"
DEBUG compile{package=gleeunit}: module_to_load_from_cache module=gleeunit/should
TRACE compile{package=gleeunit}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit@should.cache"
TRACE compile{package=gleeunit}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit@should.cache_inline"
 INFO compile{package=gleeunit}: analysing_modules count=0
DEBUG compile{package=gleeunit}: performing_code_generation
DEBUG compile{package=gleeunit}: copying_native_source_files
TRACE compile{package=gleeunit}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src"
DEBUG compile{package=gleeunit}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit_ffi.mjs"
DEBUG compile{package=gleeunit}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit@internal@reporting.erl"
DEBUG compile{package=gleeunit}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit@should.erl"
DEBUG compile{package=gleeunit}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit@internal@gleam_panic.erl"
DEBUG compile{package=gleeunit}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit.erl"
DEBUG compile{package=gleeunit}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit_ffi.erl"
DEBUG compile{package=gleeunit}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit_progress.erl"
TRACE compile{package=gleeunit}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit"
TRACE compile{package=gleeunit}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit/internal"
DEBUG compile{package=gleeunit}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit/internal/gleeunit_gleam_panic_ffi.erl"
DEBUG compile{package=gleeunit}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/gleeunit/src/gleeunit/internal/gleeunit_gleam_panic_ffi.mjs"
DEBUG compile{package=gleeunit}: skipping_entrypoint_generation
DEBUG compile{package=gleeunit}: no_erlang_to_compile
TRACE compile{package=gleeunit}: writing_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/gleeunit/ebin/gleeunit.app"
TRACE reading_file path="/home/wiskiy/dev/gleamy/server/build/packages/logging/gleam.toml"
TRACE compile{package=logging}:load: gleam_source_files "/home/wiskiy/dev/gleamy/server/build/packages/logging/src"
TRACE compile{package=logging}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/logging/src"
TRACE compile{package=logging}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/logging/_gleam_artefacts/logging.cache_meta"
TRACE compile{package=logging}: CacheFiles::modules_with_meta_files "/home/wiskiy/dev/gleamy/server/build/dev/erlang/logging/_gleam_artefacts"
TRACE compile{package=logging}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/logging/_gleam_artefacts"
DEBUG compile{package=logging}: module_to_load_from_cache module=logging
TRACE compile{package=logging}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/logging/_gleam_artefacts/logging.cache"
TRACE compile{package=logging}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/logging/_gleam_artefacts/logging.cache_inline"
 INFO compile{package=logging}: analysing_modules count=0
DEBUG compile{package=logging}: performing_code_generation
DEBUG compile{package=logging}: copying_native_source_files
TRACE compile{package=logging}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/packages/logging/src"
DEBUG compile{package=logging}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/logging/src/logging_ffi.erl"
DEBUG compile{package=logging}: skipping_unchanged_native_file_unchanged file="/home/wiskiy/dev/gleamy/server/build/packages/logging/src/logging.erl"
DEBUG compile{package=logging}: skipping_entrypoint_generation
DEBUG compile{package=logging}: no_erlang_to_compile
TRACE compile{package=logging}: writing_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/logging/ebin/logging.app"
DEBUG using_precompiled_rebar3_package package_name=telemetry
# glisten traces...
TRACE compile{package=server}:load: gleam_source_files "/home/wiskiy/dev/gleamy/server/src"
TRACE compile{package=server}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/src"
TRACE compile{package=server}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/server.cache_meta"
TRACE compile{package=server}:load: reading_file path="/home/wiskiy/dev/gleamy/server/src/server.gleam"
DEBUG compile{package=server}:load: cache_stale name="server"
TRACE compile{package=server}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/src/h2"
TRACE compile{package=server}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/src/h2/hpack"
TRACE compile{package=server}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/h2@frame.cache_meta"
TRACE compile{package=server}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/h2@hpack.cache_meta"
TRACE compile{package=server}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/h2@hpack@huffman.cache_meta"
TRACE compile{package=server}:load: reading_file path="/home/wiskiy/dev/gleamy/server/src/h2/hpack/huffman.gleam"
TRACE compile{package=server}:load: gleam_source_files "/home/wiskiy/dev/gleamy/server/test"
TRACE compile{package=server}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/test"
TRACE compile{package=server}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/server_test.cache_meta"
TRACE compile{package=server}:load: gleam_source_files "/home/wiskiy/dev/gleamy/server/dev"
TRACE compile{package=server}:load: reading_directory path="/home/wiskiy/dev/gleamy/server/dev"
TRACE compile{package=server}:load: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/build_tree.cache_meta"
TRACE compile{package=server}: CacheFiles::modules_with_meta_files "/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts"
TRACE compile{package=server}: reading_directory path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts"
DEBUG compile{package=server}: module_to_load_from_cache module=build_tree
TRACE compile{package=server}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/build_tree.cache"
TRACE compile{package=server}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/build_tree.cache_inline"
TRACE compile{package=server}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/build_tree.cache_warnings"
DEBUG compile{package=server}: module_to_load_from_cache module=h2/frame
TRACE compile{package=server}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/h2@frame.cache"
TRACE compile{package=server}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/h2@frame.cache_inline"
TRACE compile{package=server}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/h2@frame.cache_warnings"
DEBUG compile{package=server}: module_to_load_from_cache module=h2/hpack/huffman
TRACE compile{package=server}: reading_file path="/home/wiskiy/dev/gleamy/server/build/dev/erlang/server/_gleam_artefacts/h2@hpack@huffman.cache"
ERROR Failed error=MetadataDecodeError { error: Some("Message is too deeply-nested or contains cycles.") }
error: Failed to decode module metadata

A problem was encountered when decoding the metadata for one of the Gleam dependency modules.
The error from the decoder library was:

Message is too deeply-nested or contains cycles.
```

### PR DESCRIPTION
**Pull request by GearsDatapacks**
Closes #1599 and fixes #5260

- [x] The changes in this PR have been discussed beforehand in an issue
- [x] The issue for this PR has been linked
- [x] Tests have been added for new behaviour
- [x] The changelog has been updated for any user-facing changes

This PR replaces Cap'n'proto with Serde and Bincode for module caching. I have also merged the `cache_inline` and `cache_module` files into the main `.cache` as I don't see a reason for them to be kept separate anymore.

### CODE REVIEW

File: compiler-core/src/build/package_compiler.rs [hunk 1]
```diff
@@ -313,7 +312,8 @@ where
             let cache_files = CacheFiles::new(&artefact_dir, &module.name);
 
             // Write cache file
-            let bytes = ModuleEncoder::new(&module.ast.type_info).encode()?;
+            let bytes =
+                metadata::encode(&module.ast.type_info).expect("Failed to serialise module cache");
```
Comment (lpil) [inline compiler-core/src/build/package_compiler.rs]: There's a slight difference in behaviour here in that previously warnings would not be stored for dependencies, but now they are. I don't think it results in them being shown to the programmer, but it does mean we do a little bit more work to encode and decode them each time.

Probably doesn't matter? What do you think?

Comment (GearsDatapacks) [reply compiler-core/src/build/package_compiler.rs]: I have tested and they still are not shown to the programmer with this change. I can remove them from the cache as well though.

Comment (lpil) [reply compiler-core/src/build/package_compiler.rs]: Do you think it's worth doing that?

Comment (GearsDatapacks) [reply compiler-core/src/build/package_compiler.rs]: Looking at the code, removing warning caching would mean we need to clone the `ModuleInterface`, as we only have an immutable reference here. Not sure if that's a worthwhile tradeoff

Comment (lpil) [reply compiler-core/src/build/package_compiler.rs]: Couldn't we mutate it instead? Swap the vector for an empty one?

Comment (GearsDatapacks) [reply compiler-core/src/build/package_compiler.rs]: We are only given an immutable reference, so we cannot mutate it without cloning

Comment (lpil) [reply compiler-core/src/build/package_compiler.rs]: We have ownership in this class, so we don't need to clone.

It's a shame serde is so inflexible here- doesn't seem there's a way to skip over a field conditionally that lets you pass in more state.

**Comment by ankddev** [comment]
@lpil Just wondering if it's good to use bincode here, since [it's unmantained](https://rustsec.org/advisories/RUSTSEC-2025-0141.html). Some projects are migrating to alternatives and some ones are staying on it unless there are some problems with it, so maybe it's good enough for now.
