### PR TITLE
Fix #3288

### LINKED ISSUE #3288: Compiler panics when a custom type variant doesn't exist
Ran into this while working on the [Forth exercise](https://exercism.org/tracks/gleam/exercises/forth) on the exercism track.

It popped up when adding a custom type variant that held data of a type I had not yet created. Here's the full error message:

```
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
and include this error message with your report.

Panic: compiler-core/src/exhaustiveness.rs:746
	Custom type variants must exist: Type { name: "Entry", hint: AlternativeTypes(["Float", "Bool", "BitArray", "Result", "Forth", "ForthError", "Nil", "UtfCodepoint", "Int", "List", "String", "Entry"]) }
Gleam version: 1.2.0
Operating system: macos

If you can also share your code and say what file you were editing or any
steps to reproduce the crash that would be a great help.

You may also want to try again with the `GLEAM_LOG=trace` environment
variable set.
```

Here is the code prior to receiving the error:

```gleam
import gleam/int
import gleam/list
import gleam/result
import gleam/string

pub type Forth {
  Forth(stack: List(Int))
}

pub type ForthError {
  DivisionByZero
  StackUnderflow
  InvalidWord
  UnknownWord
}

type Entry {
  Value(Int)
}


pub fn new() -> Forth {
  Forth([])
}

pub fn format_stack(f: Forth) -> String {
  case f {
    Forth([]) -> ""
    Forth(stack) ->
      stack
      |> list.reverse
      |> list.map(int.to_string)
      |> string.join(" ")
  }
}

pub fn eval(f: Forth, prog: String) -> Result(Forth, ForthError) {
  let #(entry, rest) = result.unwrap(string.split_once(prog, " "), #(prog, ""))

  case f, prog {
    Forth(stack), "" -> Ok(Forth(stack))
    Forth(stack), _ -> {
      use entry <- result.try(parse_entry(entry))
      case entry {
        Value(num) -> eval(Forth([num, ..stack]), rest)
      }
    }
  }
}

fn parse_entry(entry: String) -> Result(Entry, ForthError) {
  case int.parse(entry) {
    Ok(num) -> Ok(Value(num))
    _ ->
      case entry {
        "+" -> Ok(Value(0))
        _ -> Error(InvalidWord)
      }
  }
}

```

...And the code w/ the line (`Word(Operator)`) that causes the error:

```gleam
import gleam/int
import gleam/list
import gleam/result
import gleam/string

pub type Forth {
  Forth(stack: List(Int))
}

pub type ForthError {
  DivisionByZero
  StackUnderflow
  InvalidWord
  UnknownWord
}

type Entry {
  Value(Int)
  Word(Operator)
}


pub fn new() -> Forth {
  Forth([])
}

pub fn format_stack(f: Forth) -> String {
  case f {
    Forth([]) -> ""
    Forth(stack) ->
      stack
      |> list.reverse
      |> list.map(int.to_string)
      |> string.join(" ")
  }
}

pub fn eval(f: Forth, prog: String) -> Result(Forth, ForthError) {
  let #(entry, rest) = result.unwrap(string.split_once(prog, " "), #(prog, ""))

  case f, prog {
    Forth(stack), "" -> Ok(Forth(stack))
    Forth(stack), _ -> {
      use entry <- result.try(parse_entry(entry))
      case entry {
        Value(num) -> eval(Forth([num, ..stack]), rest)
      }
    }
  }
}

fn parse_entry(entry: String) -> Result(Entry, ForthError) {
  case int.parse(entry) {
    Ok(num) -> Ok(Value(num))
    _ ->
      case entry {
        "+" -> Ok(Value(0))
        _ -> Error(InvalidWord)
      }
  }
}

```

It makes sense that my code would not compile, but it's a little surprising that it causes the compiler to panic.

Hope this report is helpful!

### PR DESCRIPTION
**Pull request by GearsDatapacks**
Fixes #3288 
This just makes the analyser more fault tolerant for custom types that reference other types that don't exist, and still registers the custom type in that case.

### CODE REVIEW

**Comment by GearsDatapacks** [comment]
There are probably other cases where a similar crash happens; I haven't really checked for places that might happen, but it might be worth looking into

File: compiler-core/src/analyse.rs [hunk 1]
```diff
@@ -839,8 +839,14 @@ impl<'a, A> ModuleAnalyzer<'a, A> {
             for (i, RecordConstructorArg { label, ast, .. }) in
                 constructor.arguments.iter().enumerate()
             {
-                // Build a type from the annotation AST
-                let t = hydrator.type_from_ast(ast, environment)?;
+                // Build a type from the annotation AST// Build a type from the annotation AST
```
Comment (lpil) [inline compiler-core/src/analyse.rs:842]: Funny comment here

**Review by lpil — COMMENTED** [review]
Hello! Thank you for this fix 💜 

For my understanding: how does this fix the crash? What was the cause?

File: compiler-core/src/analyse.rs (hunk 1 above)
Comment (GearsDatapacks) [reply compiler-core/src/analyse.rs:842]: Oops. must have accidentally copy-pasted.

**Comment by GearsDatapacks** [comment]
> For my understanding: how does this fix the crash? What was the cause?

Essentially, when the compiler ran into an error analysing a constructor, for example if it referenced a non-existent type, it would exit the function early, not getting to the piece of code that properly registers the type and constructors. Then, in the exhaustiveness checker, there was a `.expect` which relied on that registering, which then caused the crash.

I can't remember the exact details of what bit it's relying on, but this just prevents that early return.

File: compiler-core/src/analyse.rs (hunk 1 above)
Comment (GearsDatapacks) [reply compiler-core/src/analyse.rs]: I've now fixed that comment.

**Review by lpil — APPROVED** [review]
Ah that makes sense. Thank you very much
