### PR TITLE
Fix typescript generation of generic types

### LINKED ISSUE #5312: Generic in TypeScript types are not propagated to subtypes
Hi!

I figured out type-checking is lost in TypeScript declarations for nested types. Let's take an example. If I write in Gleam:

```gleam
import gleam/option.{type Option}

pub type Example(value) {
  Example(
    field1: value, 
    field2: Option(value),
  )
}
```

It gets generated to:

```typescript
export class Example<PBN> extends _.CustomType {
  /** @deprecated */
  constructor(field1: PBN, field2: $option.Option$<any>);
  /** @deprecated */
  field1: PBN;
  /** @deprecated */
  field2: $option.Option$<any>;
}
export function Example$Example<PBN>(
  field1: PBN,
  field2: $option.Option$<any>,
): Example$<PBN>;
```

While it should be compiled to:

```typescript
export class Example<PBN> extends _.CustomType {
  /** @deprecated */
  constructor(field1: PBN, field2: $option.Option$<PBN>);
  /** @deprecated */
  field1: PBN;
  /** @deprecated */
  field2: $option.Option$<PBN>;
}
export function Example$Example<PBN>(
  field1: PBN,
  field2: $option.Option$<PBN>,
): Example$<PBN>;
```

You can note it's correctly propagated for direct children of the record, but not for nested types.

### PR DESCRIPTION
**Pull request by GearsDatapacks**
Fixes #5312

- [x] The changes in this PR have been discussed beforehand in an issue
- [x] The issue for this PR has been linked
- [x] Tests have been added for new behaviour
- [x] The changelog has been updated for any user-facing changes

I also made sure generic parameters are sorted, as I noticed when reviewing the snapshot that some of the parameters were `<I, J>`, while some were `<J, I>`.

### CODE REVIEW

File: compiler-core/src/javascript/typescript.rs [hunk 1]
```diff
@@ -58,6 +58,7 @@ fn name_with_generics<'a>(
     let generic_usages = collect_generic_usages(HashMap::new(), types);
     let generic_names: Vec<Document<'_>> = generic_usages
         .keys()
+        .sorted()
```
Comment (giacomocavalieri) [inline compiler-core/src/javascript/typescript.rs:61]: Shouldn't we make sure that they appear in the same order they appear in the Gleam definition? Is this guaranteed by just using `.sorted()`?

File: compiler-core/src/javascript/typescript.rs [hunk 2]
```diff
@@ -883,32 +884,35 @@ impl<'a> TypeScriptGenerator<'a> {
         &mut self,
         type_: &Type,
         generic_usages: Option<&HashMap<u64, u64>>,
+        force_generic_id: bool,
```
Comment (giacomocavalieri) [inline compiler-core/src/javascript/typescript.rs]: Could you add a comment explaining what this does?

File: compiler-core/src/javascript/typescript.rs [hunk 3]
```diff
@@ -974,6 +980,7 @@ impl<'a> TypeScriptGenerator<'a> {
         name: &str,
         arguments: &[Arc<Type>],
         generic_usages: Option<&HashMap<u64, u64>>,
+        force_generic_id: bool,
```
Comment (giacomocavalieri) [inline compiler-core/src/javascript/typescript.rs]: Same as above, a comment would be useful!

File: compiler-core/src/javascript/typescript.rs [hunk 4]
```diff
@@ -1023,6 +1032,7 @@ impl<'a> TypeScriptGenerator<'a> {
         arguments: &[Arc<Type>],
         module: &str,
         generic_usages: Option<&HashMap<u64, u64>>,
+        force_generic_id: bool,
```
Comment (giacomocavalieri) [inline compiler-core/src/javascript/typescript.rs]: Same here!

File: compiler-core/src/javascript/typescript.rs (hunk 1 above)
Comment (GearsDatapacks) [reply compiler-core/src/javascript/typescript.rs:61]: I think it should work fine like this, seeing as it will sort by numeric value, and the compiler generates the new IDs in the same order as they are in the definition.

**Comment by GearsDatapacks** [comment]
I've replaced the boolean parameter with a custom type which is documented to explain what it does
