### PR TITLE
Better error message for call expression in case clause guard

### LINKED ISSUE #2509: Error message for using a function in `case` guard clause is unhelpful
Guard clauses (`if` inside a match arm) do not allow functions, the current error message doesn't adequately communicate this to the user:

```rust
import gleam/io
import gleam/string

pub fn main() {
  let my_string = "hello"
  case my_string {
    _ if string.length(my_string) > 2 -> io.debug("doesn't work!'")
  }
}
```

```
error: Syntax error
  ┌─ /src/main.gleam:7:23
  │
7 │     _ if string.length(my_string) > 2 -> io.debug("doesn't work!'")
  │                       ^ I was not expecting this.

Expected one of: 
"->"
Hint: Did you mean to wrap a multi line clause in curly braces?
```

Can we improve this to call out the specific error: that we're trying to use a function in a guard clause?

### PR DESCRIPTION
**Pull request by DeviousStoat**
closes  #2509

Gave it a try since the other PR was closed and I think this would be very helpful

### CODE REVIEW

File: compiler-core/src/parse.rs [hunk 1]
```diff
@@ -1395,6 +1395,21 @@ where
         }
     }
 
+    // checks if we have a function call after we find an invalid left paren
+    // Warning: this function will consume the tokens
+    // Returns the location of the right paren if we have a function call
+    fn is_invalid_call_in_case_clause_guard(&mut self) -> Option<u32> {
+        if self.parse_fn_args().is_err() {
```
Comment (lpil) [inline compiler-core/src/parse.rs:1402]: As the comment says this could consume some characters but then fail, at which point the parser is left in an "ok" state at the level up. This could result in some invalid code being "successfully" parsed.

The parser must always remain in an error state once it encounters an error.

How about making this function return a parse error instead? It would ensure it is always correct, and it removes some of the duplicated logic from the sites where this function is called

File: compiler-core/src/parse.rs [hunk 2]
```diff
@@ -1395,6 +1395,21 @@ where
         }
     }
 
+    // checks if we have a function call after we find an invalid left paren
+    // Warning: this function will consume the tokens
+    // Returns the location of the right paren if we have a function call
+    fn is_invalid_call_in_case_clause_guard(&mut self) -> Option<u32> {
```
Comment (lpil) [inline compiler-core/src/parse.rs:1401]: This name doesn't match how the other methods are named in the parser

File: compiler-core/src/parse.rs [hunk 3]
```diff
@@ -1395,6 +1395,21 @@ where
         }
     }
 
+    // checks if we have a function call after we find an invalid left paren
+    // Warning: this function will consume the tokens
+    // Returns the location of the right paren if we have a function call
```
Comment (lpil) [inline compiler-core/src/parse.rs:1400]: Doc comments use `///`. Capital letters and punctuation too please 🙏

**Review by lpil — COMMENTED** [review]
Thank you!

**Review by lpil — APPROVED** [review]
Lovely work!! Thank you very much

**Comment by lpil** [comment]
Would you mind rebasing to be up-to-date with main and also updating the changelog? Thank you

**Comment by DeviousStoat** [comment]
I rebased on main and updated the changelog

**Review by lpil — APPROVED** [review]
Beautiful!!! Thank you!!
