### PR TITLE
Fix incorrect missing patterns

### LINKED ISSUE #4278: Incorrect missing patterns given for `case` expression
To reproduce, you need this code:
```gleam
pub fn wibble(b: Bool, i: Int) {
  case b, i {
    False, 1 -> todo
    True, 2 -> todo
  }
}
```
The gleam compiler/LS gives this error:
```
The missing patterns are:

    False, _
    True, _
    _, _
```
Which is not correct. It could either give `_, _` or `False, _`/`True, _`, but both are not needed.

### PR DESCRIPTION
**Pull request by abs0luty**
Fixes [#4278](https://github.com/gleam-lang/gleam/issues/4278).

Running this code:

```gleam
pub fn wibble(b: Bool, i: Int) {
  case b, i {
    False, 1 -> todo
    True, 2 -> todo
  }
}
```

Produces this error:

```
The missing patterns are:

    False, _
    True, _
    _, _
```

Ideally, one would expect either `_, _` or `False, _` and `True, _`.

The root cause is in the pivot choice for building the decision tree. When we pivot on an infinite subject (like Int) before a finite one (like `Bool`), the "fallback" branch for the infinite split collapses to a textual `_`, which then overlaps with the more specific missing patterns discovered under the finite splits. 

The clean fix is to make the compiler prefer finite-domain subjects first when choosing the pivot. It shrinks the search space and avoids noisy fallbacks. 

So the solution is to teach `find_pivot_check` to prefer finite-branching subjects (tuples, lists, and named types with known constructors) over infinite ones (e.g. ints, floats, strings).

```gleam
pub fn wibble(b: Bool, i: Int) {
  case b, i {
    False, 1 -> todo
    True, 2 -> todo
  }
}
```

This makes `Bool` beat `Int` in the example, so the top split is on b, eliminating the top-level `_, _` catch-all that comes from an infinite fallback:

```
error: Inexhaustive patterns
  ┌─ /Users/adi.salimgereyev/hello_world/src/hello_world.gleam:6:3
  │  
6 │ ╭   case b, i {
7 │ │     False, 1 -> 1
8 │ │     True, 2 -> 2
9 │ │   }
  │ ╰───^

This case expression does not have a pattern for all possible values. If it
is run on one of the values without a pattern then it will crash.

The missing patterns are:

    False, _
    True, _
```

More about creating effective decision trees can be found [here](https://www.cs.tufts.edu/~nr/cs257/archive/luc-maranget/jun08.pdf).

### CODE REVIEW

File: compiler-core/src/exhaustiveness.rs [hunk 1]
```diff
@@ -2713,24 +2713,46 @@ impl<'a> Compiler<'a> {
...
+    env: &Environment<'_>,
+) -> Option<PatternCheck> {
+    // Count how often each variable is referenced across branches (old heuristic).
     let mut var_references = HashMap::new();
     for branch in branches {
         for check in &branch.checks {
             let _ = var_references
                 .entry(check.var.id)
-                .and_modify(|references| *references += 1)
+                .and_modify(|r| *r += 1)
```
Comment (giacomocavalieri) [inline compiler-core/src/exhaustiveness.rs]: We prefer using full names instead of shorthands in the compiler, could you revert this?

File: compiler-core/src/exhaustiveness.rs [hunk 2]
```diff
@@ -2713,24 +2713,46 @@ impl<'a> Compiler<'a> {
...
         .iter()
-        .max_by_key(|check| var_references.get(&check.var.id).cloned().unwrap_or(0))
+        .max_by_key(|check| {
+            let mode = check.var.branch_mode(env);
+            let is_finite = !mode.is_infinite();
+            let size = domain_size_hint(&mode);
+            let refs = var_references.get(&check.var.id).cloned().unwrap_or(0);
+
+            // Note: use usize::MAX - size to prefer smaller finite domains.
+            (is_finite, usize::MAX - size, refs)
```
Comment (giacomocavalieri) [inline compiler-core/src/exhaustiveness.rs]: Could you add a comment explaining why the tuple is structured this way? It's a bit hard to understand at first glance why the three items are ordered the way they are

File: compiler-core/src/exhaustiveness.rs [hunk 3]
```diff
@@ -2713,24 +2713,46 @@ impl<'a> Compiler<'a> {
...
+
     first_branch
         .checks
         .iter()
-        .max_by_key(|check| var_references.get(&check.var.id).cloned().unwrap_or(0))
+        .max_by_key(|check| {
+            let mode = check.var.branch_mode(env);
+            let is_finite = !mode.is_infinite();
+            let size = domain_size_hint(&mode);
+            let refs = var_references.get(&check.var.id).cloned().unwrap_or(0);
```
Comment (giacomocavalieri) [inline compiler-core/src/exhaustiveness.rs]: No shorthands here as well `references` instead of `refs`

File: compiler-core/src/exhaustiveness.rs [hunk 4]
```diff
@@ -2713,24 +2713,46 @@ impl<'a> Compiler<'a> {
...
-                .and_modify(|references| *references += 1)
+                .and_modify(|r| *r += 1)
                 .or_insert(0);
         }
     }
 
+    // Score each candidate in the first branch with a tuple:
+    // (is_finite, -domain_size_hint, references)
+    // Higher is better. domain_size_hint is "how many choices" the split makes.
+    fn domain_size_hint(mode: &BranchMode) -> usize {
```
Comment (giacomocavalieri) [inline compiler-core/src/exhaustiveness.rs]: Can we give this a name that's a bit easier to understand? Something like `number_of_choices` feels more descriptive of what this is doing.

And instead of defining it here I'd make it a method of `BranchMode`:
```rs
impl BranchMode {
  fn number_of_choices(&self) -> usize {
    // ...
  }
}
```

**Comment by lpil** [comment]
Brilliant, thank you! This PR is fantastic and very impressive!

I agree with Jak's feedback 🙏 

Also v interested in the literature you mentioned. We try to have this information in the code comments for complex bits of the codebase, so more documentation would be fab!

File: compiler-core/src/exhaustiveness.rs (hunk 1 above)
Comment (abs0luty) [reply compiler-core/src/exhaustiveness.rs]: Sorry didn't notice that!

File: compiler-core/src/exhaustiveness.rs (hunk 2 above)
Comment (abs0luty) [reply compiler-core/src/exhaustiveness.rs]: Sure!

File: compiler-core/src/exhaustiveness.rs (hunk 3 above)
Comment (abs0luty) [reply compiler-core/src/exhaustiveness.rs]: Sorry, fixed that!

File: compiler-core/src/exhaustiveness.rs (hunk 4 above)
Comment (abs0luty) [reply compiler-core/src/exhaustiveness.rs]: I'll just call it `BranchMode::branching_factor()`.

File: compiler-core/src/exhaustiveness.rs (hunk 2 above)
Comment (abs0luty) [reply compiler-core/src/exhaustiveness.rs]: By the way, I think `is_finite, -size` can be reduced to just `-size`, because we can set `size = usize::MAX` for infinite subjects.

**Review by giacomocavalieri — APPROVED** [review]
This is amazing, thank you!

**Comment by lpil** [comment]
I'll update the changelog for you 🙏
