### PR TITLE
Move build locks to `build` directory so open files do not interrupt clearing old builds

### LINKED ISSUE #2700: Deleting Error \build\dev\erlang
Related to https://github.com/gleam-lang/gleam/issues/2680
Gleam Version: v1.0.0
Operating System: Windows 10

Problem:
If i try to run `gleam run`, `gleam build`,  `gleam test` or `gleam check` i get Following error:
```
error: File IO failure
An error occurred while trying to delete this directory:
    Z:\...\build\dev\erlang
The error message from the file IO library was:
    Die Datei kann nicht geöffnet werden, weil sie gerade gelöscht wird. (os error 303)
```

### PR DESCRIPTION
**Pull request by ivanjermakov**
Fixes #2700 and #2680.

The cause of `Directory not empty (os error 39)` when recreating build dir within `check_gleam_version()` is that called `delete_directory` is trying to remove a directory while lock file is still open by `BuildLock::lock()`. This works ok on ext4, but fails with error on NTFS ([and perhaps BRTFS](https://github.com/gleam-lang/gleam/issues/2700#issuecomment-2317087702)) partitions.

Solution is to move lock files up in the file tree from the directory that is being removed.

New lock file paths:

```
$ROOT/build/packages/gleam.lock
$ROOT/build/gleam-dev-erlang.lock
$ROOT/build/gleam-dev-javascript.lock
$ROOT/build/gleam-prod-erlang.lock
$ROOT/build/gleam-prod-javascript.lock
$ROOT/build/gleam-lsp-erlang.lock
$ROOT/build/gleam-lsp-javascript.lock
```

### CODE REVIEW

File: compiler-cli/src/build_lock.rs [hunk 1]
```diff
@@ -8,34 +8,59 @@ use gleam_core::{
 use strum::IntoEnumIterator;
 
 #[derive(Debug)]
-pub(crate) struct BuildLock {
-    directory: Utf8PathBuf,
+pub(crate) enum BuildLock {
```
Comment (ivanjermakov) [inline compiler-cli/src/build_lock.rs:11]: Is it ok for it to be enum? Or we can construct `lock_filename` right in the constructor

Comment (lpil) [reply compiler-cli/src/build_lock.rs:11]: Making the path in the constructor sounds good to me

**Review by lpil — COMMENTED** [review]
Wonderful work, thank you! Would you mind updating the CHANGELOG file also? Thanks

**Comment by GearsDatapacks** [comment]
Fyi merge commits are not allowed in this repo. You'll need to rebase to remove them before this PR will be merged

**Comment by ivanjermakov** [comment]
@GearsDatapacks thanks, I missed that when checking `CONTRIBUTING.md`.

**Comment by GearsDatapacks** [comment]
Scanning through, it doesn't look like it's mentioned. I want to improve upon the contributing documents at some point, so maybe I'll try and add that

**Review by lpil — APPROVED** [review]
Perfect, thank you!
