### PR TITLE
fix: formatter moves comments out of tuple return type

### LINKED ISSUE #5004: Formatter moves comments out of tuple return types
I found a couple odd cases with the formatter when adding comments inside of tuple return types.

Both of these inputs...

```gleam
fn parse_data(str: String) -> #(
  List(String), // qualifications
) {
  todo
}
```
```gleam
fn parse_data(str: String) -> #(
  // qualifications
  List(String),
) {
  todo
}
```

...yield this output:

```gleam
fn parse_data(
  str: String,
  // qualifications
) -> #(List(String)) {
  todo
}
```

I get the same results using either `gleam format` from the command line (Gleam 1.12.0) or "Format Document" in VSCode (VSCode 1.104.0; Gleam VSCode extension 2.12.1).

### PR DESCRIPTION
**Pull request by ankddev**
Closes #5004 
Fix formatting of tuple return types: now comments are not moved out.
### Showcase
```
$ cat src\test_gleam.gleam
import gleam/io

pub fn main() -> Nil {
  io.println("Hello from test_gleam!")
}

pub fn hello() -> #(
  // test 0
  String, // test 1
) {
  #("hello")
}

$ ..\..\RustroverProjects\gleam\target\debug\gleam format

$ cat src\test_gleam.gleam
import gleam/io

pub fn main() -> Nil {
  io.println("Hello from test_gleam!")
}

pub fn hello() -> #(
  String,
  // test 0
  // test 1
) {
  #("hello")
}
```

### CODE REVIEW

**Review by ankddev — COMMENTED** [review]
@lpil I marked this PR as draft since I have some questions.

Firstly, is it acceptable that comments in tuple return type move to the end of tuple, right before closing `)`? I found that basic tuple format as following:
```gleam
// Before formatting
#(
  // hello 0
  "hello" // hello 1
  // hello 2
)
// After formatting
#(
  // hello 0
  "hello",
  // hello 1
  // hello 2
)
```
I have no idea at how to place them better.

Secondly, I don't know why test is failed. There are no snapshots for this test generated. I checked other PRs with formatter changes and it seems like that code in `assert_format!()` must be equal to the result of formatting? Am I right?

**Comment by lpil** [comment]
Yup that's the correct formatting! Let me know if you're ready for a review 🙏

**Comment by ankddev** [comment]
@lpil Ready for review!

File: compiler-core/src/format.rs [hunk 1]
```diff
@@ -834,7 +834,18 @@ impl<'comments> Formatter<'comments> {
                     .expect("Function in a statement must be named")
                     .1,
             )
-            .append(self.wrap_arguments(arguments, function.location.end));
+            .append(
+                self.wrap_arguments(
+                    // We count end location of arguments here.
+                    // Before this change, wrap_arguments consumed all comments
+                    // leading in moving comments from return annotation to argument list
```
Comment (lpil) [inline compiler-core/src/format.rs]: Document the current code, not the code of the past!

What does "we count end location of arguments here" mean?

**Review by lpil — COMMENTED** [review]
Thank you! Code looks super clean. One tiny note below.

File: compiler-core/src/format.rs (hunk 1 above)
Comment (ankddev) [reply compiler-core/src/format.rs]: @lpil Done

**Review by lpil — APPROVED** [review]
Super nice!! Thank you
