### PR TITLE
fix: add correct constraints for pre-release versions

### LINKED ISSUE #4220: `gleam add` adds incorrect constraint for release candidate versions
# Steps to reproduce
- Add time to the project: `gleam add gleam_time`
- Run `gleam update`

Will add the following line in the toml file:

```toml
name = "splittable_fe"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.5.0 and < 5.0.0"
gleam_json = ">= 1.0.1 and < 3.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
rsvp = ">= 1.0.1 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.5.7 and < 2.0.0"
```

gleam_time latest version is `-rc2` so it should actually add something like this:
```toml
gleam_time = ">= 1.0.0-rc2 and < 2.0.0"
```

When changing this manually it can now successfully update.

# Version running
gleam 1.8.0

# Logs
This is the output of the `gleam update` command when not changing the dependency manually:
```txt
DEBUG download_deps: locking_directory path="/home/norlock/projects/splittable/splittable_fe/build/packages/gleam.lock"
TRACE download_deps: reading_file path="/home/norlock/projects/splittable/splittable_fe/gleam.toml"
DEBUG download_deps: ignoring_manifest
  Resolving versions
 INFO download_deps: resolving_versions
DEBUG download_deps: looking_up_hex_package package="gleeunit"
TRACE download_deps: checkout waiting for idle connection: ("https", repo.hex.pm)
DEBUG download_deps: starting new connection: https://repo.hex.pm/
TRACE download_deps: Http::connect; scheme=Some("https"), host=Some("repo.hex.pm"), port=None
DEBUG download_deps: connecting to [2a04:4e42:12::514]:443
DEBUG download_deps: connected to [2a04:4e42:12::514]:443
TRACE download_deps: http1 handshake complete, spawning background dispatcher task
TRACE download_deps: checkout dropped for ("https", repo.hex.pm)
TRACE download_deps: put; add idle connection for ("https", repo.hex.pm)
DEBUG download_deps: pooling idle connection for ("https", repo.hex.pm)
DEBUG download_deps: looking_up_hex_package package="gleam_regexp"
TRACE download_deps: take? ("https", repo.hex.pm): expiration = Some(90s)
DEBUG download_deps: reuse idle connection for ("https", repo.hex.pm)
TRACE idle interval checking for expired
TRACE download_deps: put; add idle connection for ("https", repo.hex.pm)
DEBUG download_deps: pooling idle connection for ("https", repo.hex.pm)
DEBUG download_deps: looking_up_hex_package package="rsvp"
TRACE download_deps: take? ("https", repo.hex.pm): expiration = Some(90s)
DEBUG download_deps: reuse idle connection for ("https", repo.hex.pm)
TRACE put; add idle connection for ("https", repo.hex.pm)
DEBUG pooling idle connection for ("https", repo.hex.pm)
DEBUG download_deps: looking_up_hex_package package="gleam_time"
TRACE download_deps: take? ("https", repo.hex.pm): expiration = Some(90s)
DEBUG download_deps: reuse idle connection for ("https", repo.hex.pm)
TRACE download_deps: put; add idle connection for ("https", repo.hex.pm)
DEBUG download_deps: pooling idle connection for ("https", repo.hex.pm)
DEBUG download_deps: looking_up_hex_package package="lustre_dev_tools"
TRACE download_deps: take? ("https", repo.hex.pm): expiration = Some(90s)
DEBUG download_deps: reuse idle connection for ("https", repo.hex.pm)
TRACE put; add idle connection for ("https", repo.hex.pm)
DEBUG pooling idle connection for ("https", repo.hex.pm)
DEBUG download_deps: looking_up_hex_package package="lustre"
TRACE download_deps: take? ("https", repo.hex.pm): expiration = Some(90s)
DEBUG download_deps: reuse idle connection for ("https", repo.hex.pm)
TRACE put; add idle connection for ("https", repo.hex.pm)
DEBUG pooling idle connection for ("https", repo.hex.pm)
DEBUG download_deps: looking_up_hex_package package="gleam_json"
TRACE download_deps: take? ("https", repo.hex.pm): expiration = Some(90s)
DEBUG download_deps: reuse idle connection for ("https", repo.hex.pm)
TRACE put; add idle connection for ("https", repo.hex.pm)
DEBUG pooling idle connection for ("https", repo.hex.pm)
DEBUG download_deps: looking_up_hex_package package="gleam_stdlib"
TRACE download_deps: take? ("https", repo.hex.pm): expiration = Some(90s)
DEBUG download_deps: reuse idle connection for ("https", repo.hex.pm)
TRACE put; add idle connection for ("https", repo.hex.pm)
DEBUG pooling idle connection for ("https", repo.hex.pm)
ERROR Failed error=DependencyResolutionFailed("Unable to find compatible versions for the version constraints in your\ngleam.toml. The conflicting packages are:\n\n- splittable_fe\n- gleam_time\n")
error: Dependency resolution failed

An error occurred while determining what dependency packages and
versions should be downloaded.
The error from the version resolver library was:

Unable to find compatible versions for the version constraints in your
gleam.toml. The conflicting packages are:

- splittable_fe
- gleam_time
```

### PR DESCRIPTION
**Pull request by ankddev**
Closes #4220. It's very simple fix, I've just replaced manual version construction with `Display` implementation for `Version`.
***
- [x] The changes in this PR have been discussed beforehand in an issue
- [x] The issue for this PR has been linked
- [x] Tests have been added for new behaviour
- [x] The changelog has been updated for any user-facing changes

### CODE REVIEW

File: compiler-cli/src/add.rs [hunk 1]
```diff
@@ -58,13 +58,7 @@ pub fn command(paths: &ProjectPaths, packages_to_add: Vec<String>, dev: bool) ->
...
         // Produce a version requirement locked to the major version.
         // i.e. if 1.2.3 is selected we want >= 1.2.3 and < 2.0.0
-        let range = format!(
-            ">= {}.{}.{} and < {}.0.0",
-            version.major,
-            version.minor,
-            version.patch,
-            version.major + 1
-        );
+        let range = format!(">= {} and < {}.0.0", version, version.major + 1);
```
Comment (lpil) [inline compiler-cli/src/add.rs]: `Display` is for debugging and can be unstable, so it's not usable for business logic.

Comment (ankddev) [reply compiler-cli/src/add.rs]: Oh, yeah! One other question: should this new function be used in `Display` for now as well?

Comment (lpil) [reply compiler-cli/src/add.rs]: No, display should be left as the default 🙏

Comment (ankddev) [reply compiler-cli/src/add.rs]: Okay, thank you, will do it!

**Comment by ankddev** [comment]
@lpil I think that it's done now. I've created a new function in `add.rs` (don't like the name, to be honest) and two tests
