### PR TITLE
Fix path dependency paths

### LINKED ISSUE #2182: manifest.toml uses absolute paths for path deps
Follows on from https://github.com/gleam-lang/gleam/pull/2153

These need to be relative.

```toml
packages = [
  { name = "project_b", version = "0.1.0", build_tools = ["gleam"], requirements = ["project_d"], source = "local", path = "/Users/louis/src/gleam/gleam/test/project_path_deps/project_b" },
]
```

### PR DESCRIPTION
**Pull request by NthTensor**
Resolves #2182.

This adds a dependency to the [pathdiff](https://docs.rs/pathdiff) package, a utility for turning absolute paths into relative ones. Normally I don't like to add tiny packages like this in PRs but in this case its a somewhat complex implementation extracted from the rust compiler backed so I feel it's warranted.

### CODE REVIEW

**Comment by NthTensor** [comment]
Gah! I am not sure why windows is failing.

**Review by lpil — COMMENTED** [review]
`%s/relitive/relative/g` 😁

**Comment by lpil** [comment]
Ah, very cool! Is that something to be done in this PR?

**Comment by NthTensor** [comment]
Yeah, I can't test it but I am pretty sure this is currently properly broken on windows. I will mark for review when I've got it working!

**Comment by NthTensor** [comment]
Ok, should be fixed on windows. Packages given by absolute paths will still show up as absolute in the manifest, but now relative paths will stay relative.

File: compiler-cli/src/dependencies.rs [hunk 1]
```diff
@@ -612,9 +613,32 @@ impl ProvidedPackageSource {
...
+                ProvidedPackageSource::Git {
+                    repo: own_repo,
+                    commit: own_commit,
+                },
+                ProvidedPackageSource::Git {
+                    repo: other_repo,
+                    commit: other_commit,
+                },
+            ) => own_repo == other_repo && own_commit == other_commit,
+            _ => false,
```
Comment (lpil) [inline compiler-cli/src/dependencies.rs:633]: Can we list al the cases rather than having a catch all here? We've had multiple bugs from variants being added but matches like these silently returning the wrong value rather than having to be modified for the new variant.

**Review by lpil — APPROVED** [review]
Thanks! One small note, but actually I'll do it :)
