### PR TITLE
Fix invalid erlang when shadowing the bit pattern's size variable

### LINKED ISSUE #3315: Invalid Erlang generated with shadowed variables in bit patterns
```gleam
pub fn go(code) {
  let pre = 1
  case code {
    <<pre:bytes-size(pre), _:bytes>> -> pre
    _ -> panic
  }
}
```

Generates this invalid Erlang:

```erlang
go(Code) ->
    Pre = 1,
    case Code of
        <<Pre@1:Pre@1/binary, _/binary>> ->
            Pre@1;

        _ ->
            erlang:error(#{gleam_error => panic,
                    message => <<"panic expression evaluated"/utf8>>,

                    function => <<"go"/utf8>>,
                    line => 5})
    end.
```

Note how `Pre@1` is being used for the size, not `Pre`.

### PR DESCRIPTION
**Pull request by Eingin**
This closes #3315

When using the `size(x)` option on a bit array pattern. If the size option is passed a variable, and that variable is shadowed by the pattern segment the compiler will use the new shadowed name. This happens since the the usage of the already defined variable comes after the definition of the pattern's variable. It will therefore cause the compiler to use the new shadowed name instead of the intended previous name.

```gleam
let pre = 1
..
<<pre:bytes-size(pre), _:bytes>>
```
This currently creates
```erlang
<<Pre@1:Pre@1/binary, _/binary>>
```

To fix this I have moved the creation of the erlang output for the size portion before the value part. This will ensure that the previous variable name is used.

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Thank you!

Rather than iterating over the options and cloning the size how about passing in the value as a function that takes no arguments? Then it'll be computed after the options without doing extra work, and it'll be a bit simpler

**Comment by Eingin** [comment]
Yeah lets do that! I've updated the PR so now the value is passed as a function. I had to refactor the way `bit_array_segment` function works. Unfortunately now that there are multiple closures. One for the value and one for the size. The borrow checker doesn't like the multiple mutable refs with the printing. So it now takes in a printer function since the various uses of it have different requirements/dependencies for the output.

File: compiler-core/src/erlang.rs [hunk 1]
```diff
@@ -610,67 +614,72 @@ fn expr_segment<'a>(
...
-fn bit_array_segment<'a, Value: 'a, SizeToDoc, UnitToDoc>(
-    mut document: Document<'a>,
+fn bit_array_segment<'a, Value: 'a, ValueType, ValueToDoc, SizeToDoc, UnitToDoc>(
+    mut value_to_doc: ValueToDoc,
     options: &'a [BitArrayOption<Value>],
     mut size_to_doc: SizeToDoc,
     mut unit_to_doc: UnitToDoc,
     value_is_a_string_literal: bool,
-    env: &mut Env<'a>,
+    print_value: &mut dyn FnMut(&'a ValueType) -> Document<'a>,
```
Comment (lpil) [inline compiler-core/src/erlang.rs:677]: How come these are using dynamic dispatch now?

File: compiler-core/src/erlang.rs [hunk 2]
```diff
@@ -610,67 +614,72 @@ fn expr_segment<'a>(
...
 ) -> Document<'a>
 where
-    SizeToDoc: FnMut(&'a Value, &mut Env<'a>) -> Option<Document<'a>>,
+    ValueToDoc: FnMut(&mut dyn FnMut(&'a ValueType) -> Document<'a>) -> Document<'a>,
+    SizeToDoc:
+        FnMut(&'a Value, &mut dyn FnMut(&'a ValueType) -> Document<'a>) -> Option<Document<'a>>,
```
Comment (lpil) [inline compiler-core/src/erlang.rs:682]: Please revert these to the previous signature and add an addition function type here rather than using dynamic dispatch for `print_value`.

Comment (Eingin) [reply compiler-core/src/erlang.rs:682]: @lpil 
Unfortunately we cant remove the dynamic dispatch. Since the `ValueToDoc` & `SizeToDoc` are closures they don't let us use generics for passing the `print_value` into them. If we try what your proposing, the borrow checker gives us [E0782](https://doc.rust-lang.org/error_codes/E0782.html) at the `ValueToDoc` & `SizeToDoc` definitions. 

Im not sure how best to solve this, I'll try think about it today and come up with something. Buy any recommendations would be helpful.

Comment (lpil) [reply compiler-core/src/erlang.rs:682]: `print_value` should not be passed to them, it should continue to work as before.

**Comment by lpil** [comment]
Hello! Are you still working on this?

**Comment by Eingin** [comment]
@lpil Sorry for the slow response.
I have pushed a new version of the changes but looks like I somehow accidentally closed this PR. Can you Re-open it up?
 
I've changed it to wrap the the creation of the document in a closure. The only thing I'm not totally sure on are the `RefCell`s i had to add for the parameters used in the `pattern_segment` part. We cant follow the current pattern of passing in the variables into the `bit_array_segment` since there are exclusively used only by this function. If you have a better idea on how to let the borrow checker be happy do let me know.

**Comment by GearsDatapacks** [comment]
I'm pretty sure you can re-open it yourself

**Comment by Eingin** [comment]
> I'm pretty sure you can re-open it yourself

Nope, the re-open button is disabled for me unfortunately.

**Review by lpil — APPROVED** [review]
Beautiful, thank you very much
