### PR TITLE
make sure formatter no longer stack overflows when formatting big lists

### LINKED ISSUE #5297: Formatter stack overflows with long lists
When trying to format a long list with many literal items (from my tests the tipping point seems to be around 8000 items, but I'm guessing it will depend on the specific machine this runs on) the formatter fails with a stack overflow. I'm working on a fix!

### PR DESCRIPTION
**Pull request by giacomocavalieri**
This PR closes #5297.
This seems to be a really straightforward fix: the `docvec!` macro ended up creating deeply nested documents `vec(vec(vec(vec(...), ...), ...), ...)`. Now if the first item passed to the macro is a vector, it behaves the same as appending to that vector rather than creating a new vector every single time!

- [x] The changes in this PR have been discussed beforehand in an issue
- [X] The issue for this PR has been linked
- [X] Tests have been added for new behaviour
- [X] The changelog has been updated for any user-facing changes

### CODE REVIEW

File: compiler-core/src/pretty.rs [hunk 1]
```diff
@@ -56,8 +56,21 @@ macro_rules! docvec {
...
+    };
+
+    // A docvec![] with multiple elements.
+    ($first:expr, $($rest:expr),+ $(,)?) => {
+        // A document that looks like this: `Vec[Vec[..rest], ..other_rest]`
+        // is exactly the same as a flat: `Vec[..rest, ..other_rest]`.
+        // So in case a `docvec!` starts with a `Vec` we flatten it out to avoid
+        // having deeply nested documents.
+        match $first.to_doc() {
+            first@Document::Vec(_) => first.append(docvec![$($rest.to_doc()),+]),
```
Comment (lpil) [inline compiler-core/src/pretty.rs]: Why not append all the items to the inner vector instead of recursively calling the macro?

**Review by lpil — COMMENTED** [review]
Quick question inline!

File: compiler-core/src/pretty.rs (hunk 1 above)
Comment (giacomocavalieri) [reply compiler-core/src/pretty.rs]: This way we can flatten all vectors at the top of the macro: 
```
docvec![vec1, vec2, a, b] // becomes =>
vec1.append(vec2.append(vec![a, b]))
// Meaning the first two vectors are flattened out, rather than only the first one
```

Comment (lpil) [reply compiler-core/src/pretty.rs]: That moves the elements multiples times needlessly, potentially allocating new vectors and copying the existing elements each time. If the `Vec` is worked with directly it allocates at most once, and moves the new elements once. Is there a reason to do more work to restructure the tree?

Comment (giacomocavalieri) [reply compiler-core/src/pretty.rs]: Mhm you're right and just doing it for the first element seems to be fixing the issue anyway. I'll change it to that!

File: compiler-core/src/pretty.rs [hunk 2]
```diff
@@ -68,7 +68,7 @@ macro_rules! docvec {
         // So in case a `docvec!` starts with a `Vec` we flatten it out to avoid
         // having deeply nested documents.
         match $first.to_doc() {
-            first@Document::Vec(_) => first.append(docvec![$($rest.to_doc()),+]),
+            first@Document::Vec(_) => first.append(Document::Vec(vec![$($rest.to_doc()),+])),
```
Comment (lpil) [inline compiler-core/src/pretty.rs]: This is still allocating a new vector and copying everything twice! Mutate the inner vec instead and push each item directly to it.

Comment (giacomocavalieri) [reply compiler-core/src/pretty.rs]: Oooh I see what you meant let me fix that real quick

Comment (giacomocavalieri) [reply compiler-core/src/pretty.rs]: Should be good for real this time!
