### PR TITLE
Fixes #4984

### LINKED ISSUE #4984: Hint for TS-style return value type annotation
Someone coming from TypeScript can write following code:
```gleam
import gleam/io

pub fn main(): Nil {
  io.println("Hello from test_gleam!")
}
```
In this case compiler gives this unhelpful message:
```
error: Syntax error
  ┌─ C:\Users\user\projects\test_gleam\src\test_gleam.gleam:3:14
  │
3 │ pub fn main(): Nil {
  │              ^ I was not expecting this

Found `:`, expected one of:
- An import, const, type, or function.
```
I think that it would be better if error message will be something like:
```
error: Syntax error
  ┌─ C:\Users\user\projects\test_gleam\src\test_gleam.gleam:3:14
  │
3 │ pub fn main(): Nil {
  │              ^ I was not expecting this

Found `:`, expected one of:
- An import, const, type, or function.
Hint: Maybe you meant to write return value type annotation?
Return type annotations are written using `->`, not `:`
```

### PR DESCRIPTION
**Pull request by baraich**
When trying to specify return types for a function using a `:`, it now displays a better error message.

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Thank you! Could you use an `if let Some` with an early `return` for this please, similar to the error above for `FunctionDefinitionAngleGenerics`.

We'll need tests to be added too. The ones for `FunctionDefinitionAngleGenerics` would be a good example for what they would look like, you can see them in this PR https://github.com/gleam-lang/gleam/pull/4818

**Comment by baraich** [comment]
@lpil, I need your help in writing tests for these changes.  I have written the following test; however, it is failing. 

```rust
#[test]
fn wrong_function_return_type_declaration_using_colon_instead_of_right_arrow() {
    assert_module_error!(
        r#"
pub fn main(): Nil {}
        "#
    );
}

```

**Comment by GearsDatapacks** [comment]
You probably need to accept the snapshot. We use snapshot testing in the Gleam compiler, so once you run the test, you need to run `cargo insta review`. Then you look at the output (in this case the error message) and you decide whether or not it is correct. See `docs/compiler/README.md` for more information

**Comment by baraich** [comment]
@GearsDatapacks, please review the pull request.

File: compiler-core/src/parse.rs [hunk 1]
```diff
@@ -2117,6 +2117,22 @@ where
         )?;
         let (_, rpar_e) =
             self.expect_one_following_series(&Token::RightParen, "a function parameter")?;
+
+        // Check for TypeScript-style return type annotation (:) instead of arrow (->)
+        if let Some((colon_start, colon_end)) = self.maybe_one(&Token::Colon) {
+            return Err(ParseError {
+                error: ParseErrorType::UnexpectedToken {
+                    token: Token::Colon,
+                    expected: vec!["->".into()],
```
Comment (GearsDatapacks) [inline compiler-core/src/parse.rs]: We usually wrap operators in backticks like this as it makes them easier to read

```suggestion
                    expected: vec!["`->`".into()],
```

**Review by GearsDatapacks — COMMENTED** [review]
Looks good! One tiny note

**Comment by baraich** [comment]
@GearsDatapacks, I have updated the code with the suggested change.

**Review by GearsDatapacks — APPROVED** [review]
Looks good to me! Need Louis to review it before merging though

**Comment by baraich** [comment]
@lpil Please review the pull request.

File: compiler-core/src/parse.rs [hunk 2]
```diff
@@ -2117,6 +2117,22 @@ where
...
         let (_, rpar_e) =
             self.expect_one_following_series(&Token::RightParen, "a function parameter")?;
+
+        // Check for TypeScript-style return type annotation (:) instead of arrow (->)
+        if let Some((colon_start, colon_end)) = self.maybe_one(&Token::Colon) {
+            return Err(ParseError {
+                error: ParseErrorType::UnexpectedToken {
+                    token: Token::Colon,
+                    expected: vec!["`->`".into()],
+                    hint: Some("Maybe you meant to write return value type annotation?\nReturn type annotations are written using `->`, not `:`".into()),
```
Comment (lpil) [inline compiler-core/src/parse.rs]: Hmm. I think we assume they are writing an annotation here? Perhaps we can write this then.

```suggestion
                    hint: Some("Return type annotations are written using `->`, not `:`".into()),
```

**Review by lpil — APPROVED** [review]
Lovely work! Thank you very much!

I've left one tiny note inline, and would you mind updating the changelog too please 🙏

**Comment by lpil** [comment]
Ah! The build is failing because of a CI problem. If you rebase on main to the latest code changes then it should be fixed.

**Comment by baraich** [comment]
@lpil, I will rebase it on the main branch and update the [CHANGELOG.md](https://github.com/gleam-lang/gleam/blob/main/CHANGELOG.md) file.

**Comment by baraich** [comment]
@lpil, Please review the pull request.

**Comment by lpil** [comment]
You've done a merge commit rather than a rebase, so the build is failing as we do not permit them. Could you rebase on main please 🙏 That will remove the merge commit for you.

**Comment by baraich** [comment]
@lpil, I have no idea how to perform a rebase. Now, how do I revert the accidental merge? I just ran `git pull --rebase` on the main branch.

**Comment by inoas** [comment]
@baraich I think we could possibly help you out on community discord.

**Comment by baraich** [comment]
@inoas, is there an invite link?

**Comment by inoas** [comment]
> @inoas, is there an invite link?

https://gleam.run/community/

**Comment by ankddev** [comment]
@baraich https://discord.gg/gyhPbVBSzS

**Comment by lpil** [comment]
Hello! Are you still working on this one? I could help with rebasing if you like @baraich

**Comment by lpil** [comment]
I did the rebase!

**Review by lpil — APPROVED** [review]
Thank you!!!
