### PR TITLE
Fix exact package resolution for rc candidates

### LINKED ISSUE #2630: Gleam downloads wrong dependency RC version
This occurs on Gleam 0.34.1 and 1.0.0 RC2.

The `gleam.toml`:

```toml
name = "dep_test"
version = "1.0.0"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
lustre = "4.0.0-rc.2"
gleam_json = "~> 0.7"

[dev-dependencies]
gleeunit = "~> 1.0"
```

Run `gleam deps download`. The created manifest:

```toml
# This file was generated by Gleam
# You typically do not need to edit this file

packages = [
  { name = "argv", version = "1.0.1", build_tools = ["gleam"], requirements = [], otp_app = "argv", source = "hex", outer_checksum = "A6E9009E50BBE863EB37D963E4315398D$
  { name = "filepath", version = "0.2.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "filepath", source = "hex", outer_checksum = "FC1B1B29438$
  { name = "gleam_community_ansi", version = "1.4.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "gleam_community_colour"], otp_app = "gleam_community_an$
  { name = "gleam_community_colour", version = "1.3.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleam_community_colour", source = "hex", o$
  { name = "gleam_erlang", version = "0.24.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleam_erlang", source = "hex", outer_checksum = "26$
  { name = "gleam_json", version = "0.7.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "thoas"], otp_app = "gleam_json", source = "hex", outer_checksum =$
  { name = "gleam_otp", version = "0.9.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "gleam_erlang"], otp_app = "gleam_otp", source = "hex", outer_check$
  { name = "gleam_stdlib", version = "0.36.0", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "C0D14D807FEC6F8A$
  { name = "glearray", version = "0.2.1", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "glearray", source = "hex", outer_checksum = "908154F695D$
  { name = "gleeunit", version = "1.0.2", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleeunit", source = "hex", outer_checksum = "D364C87AFEB$
  { name = "glint", version = "0.16.0", build_tools = ["gleam"], requirements = ["snag", "gleam_stdlib", "gleam_community_colour", "gleam_community_ansi"], otp_app = "$
  { name = "justin", version = "1.0.1", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "justin", source = "hex", outer_checksum = "7FA0C6DB78640C6$
  { name = "lustre", version = "4.0.0-rc1", build_tools = ["gleam"], requirements = ["gleam_json", "gleam_stdlib", "argv", "glint", "filepath", "gleam_community_ansi",$
  { name = "repeatedly", version = "2.1.1", build_tools = ["gleam"], requirements = [], otp_app = "repeatedly", source = "hex", outer_checksum = "38808C3EC382B0CD98133$
  { name = "shellout", version = "1.6.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "shellout", source = "hex", outer_checksum = "E2FCD18957F$
  { name = "simplifile", version = "1.5.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "simplifile", source = "hex", outer_checksum = "EB9AA8E$
  { name = "snag", version = "0.3.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "snag", source = "hex", outer_checksum = "54D32E16E33655346AA$
  { name = "spinner", version = "1.1.0", build_tools = ["gleam"], requirements = ["gleam_erlang", "gleam_stdlib", "gleam_community_ansi", "repeatedly", "glearray"], ot$
  { name = "thoas", version = "0.4.1", build_tools = ["rebar3"], requirements = [], otp_app = "thoas", source = "hex", outer_checksum = "4918D50026C073C4AB1388437132C7$
  { name = "tom", version = "0.3.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "tom", source = "hex", outer_checksum = "0831C73E45405A2153091$
]

[requirements]
gleam_json = { version = "~> 0.7" }
gleam_stdlib = { version = "~> 0.34 or ~> 1.0" }
gleeunit = { version = "~> 1.0" }
lustre = { version = "4.0.0-rc.2" }
```

The issue is

> name = "lustre", version = "4.0.0-rc1"

As can be seen, Lustre RC1 was downloaded, even though the dependency is exact and points to RC2.

### PR DESCRIPTION
**Pull request by Acepie**
Closes #2630

Stores any versions that were set to exact releases and filters the available list if an exact release is found

### CODE REVIEW

File: compiler-core/src/dependency.rs [hunk 1]
```diff
@@ -57,6 +64,25 @@ where
     Ok(packages)
 }
 
+// If the string would parse to an exact version then return the version
+fn parse_exact_version(ver: &str) -> Option<Version> {
```
Comment (Acepie) [inline compiler-core/src/dependency.rs:68]: This feels bad/unnecessary but it doesn't seem like there is a good way to get the version out of the pubgrub parse directly

File: compiler-core/src/dependency.rs [hunk 2]
```diff
@@ -127,6 +153,7 @@ struct DependencyProvider<'a> {
     packages: RefCell<HashMap<EcoString, hexpm::Package>>,
     remote: Box<dyn PackageFetcher>,
     locked: &'a HashMap<EcoString, Version>,
+    exact_only: &'a HashMap<String, Version>,
```
Comment (Acepie) [inline compiler-core/src/dependency.rs:156]: I added a separate map here because I wasn't sure if modifying the way we create locked would make sense/cause issues elsewhere

**Review by lpil — COMMENTED** [review]
Nice! Thank you! Could add a bunch of comments to each section explaining the intent and why each bit is being done. This is general good practice but we especially want it here as it's confusing as to why we would do this.
