### PR TITLE
Fix crash in "pattern match on variable code action"

### LINKED ISSUE #5042: Language server crash when triggering "Pattern match on vairable" code action
I noticed a bug where the language server sometimes triggers when trying to trigger a code action. The minimal example I can find is the following:
```gleam
pub type Wibble {
  Wibble(Wobble)
}

pub type Wobble {
  Wobble
  Wubble
}

pub fn main() {
  let Wibble(wobble) = todo
  //         ^ Trigger code action here

  case todo {
    _ -> todo
  }
}
```
(Here the `case` expression is important for some unknown reason, and without it the bug does not occur)

Version: Latest `main` 195c44abaf4faca7edf2ca2bccfbce90c4be115f

Error message:
```
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
and include this error message with your report.

Panic: /home/gears/projects/gleam/gleam/compiler-core/src/language_server/code_action.rs:4691
	assertion failed: self.is_char_boundary(n)
Gleam version: 1.13.0-rc1
Operating system: linux

If you can also share your code and say what file you were editing or any
steps to reproduce the crash that would be a great help.
```

This is a bug with the "Pattern match on variable code action", as indicated by the line of the crash: https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/language_server/code_action.rs#L4691

### PR DESCRIPTION
**Pull request by giacomocavalieri**
This PR closes #5042

### CODE REVIEW

File: compiler-core/src/language_server/tests/action.rs [hunk 1]
```diff
@@ -7538,6 +7538,34 @@ fn map(list: List(a), fun: fn(a) -> b) { todo }
...
+}
+
+pub type Wobble {
+    Wobble
+    Wubble
+}
+
+pub fn main() {
+    let Wibble(wobble) = todo
+    //         ^ Trigger code action here
```
Comment (GearsDatapacks) [inline compiler-core/src/language_server/tests/action.rs]: Probably don't need this comment as the snapshot formatter already tells you where the code action is being triggered

Comment (giacomocavalieri) [reply compiler-core/src/language_server/tests/action.rs]: Right, I'll remove that!

**Review by lpil — APPROVED** [review]
Thank you!
