### PR TITLE
Fix slightly wrong error message for missing main function in test module

### LINKED ISSUE #4420: Slightly wrong error message for missing `main` function in test module
When running `gleam test`, if the `project_test` module doesn't have a `main` function, this error is printed:
```txt
error: Module does not have a main function

`project_test` does not have a main function so the module can not be run.
Hint: Add a public `main` function to to `src/project_test.gleam`.
```
Which isn't quite correct, as the file is `test/project_test.gleam` not `src/project_test.gleam`

### PR DESCRIPTION
**Pull request by scristobal**
resolves #4420

### CODE REVIEW

File: compiler-core/src/build.rs [hunk 1]
```diff
@@ -572,6 +572,18 @@ impl Origin {
     }
 }
 
+impl Display for Origin {
```
Comment (lpil) [inline compiler-core/src/build.rs:575]: Don't ever implement traits please! Prefer regular methods are they are much clearer.

File: compiler-core/src/type_.rs [hunk 2]
```diff
@@ -1569,6 +1570,7 @@ fn assert_suitable_main_function(
 ) -> Result<(), crate::Error> {
     let not_found = || crate::Error::ModuleDoesNotHaveMainFunction {
         module: module_name.clone(),
+        origin: Origin::Src,
```
Comment (lpil) [inline compiler-core/src/type_.rs:1573]: This is hard-coded to src, but it could be one of the others origins. It'll need to be passed in.

File: CHANGELOG.md [hunk 3]
```diff
@@ -30,6 +30,9 @@
 
   ([Giacomo Cavalieri](https://github.com/giacomocavalieri))
 
+- Fix slightly wrong error message for missing main function in dev module.
+  ([Samuel Cristobal](https://github.com/scristobal))
```
Comment (lpil) [inline CHANGELOG.md:34]: In the bug fix section please 🙏

**Review by lpil — COMMENTED** [review]
Thank you! Few small notes.

File: compiler-core/src/build.rs (hunk 1 above)
Comment (scristobal) [reply compiler-core/src/build.rs]: indeed! added a `.folder_name` method to `Origin`

thanks for the feedback

File: compiler-core/src/type_.rs (hunk 2 above)
Comment (scristobal) [reply compiler-core/src/type_.rs]: uuupppps 🙃 added as parameter to the assertion, also adapted existing tests using it

File: CHANGELOG.md (hunk 3 above)
Comment (scristobal) [reply CHANGELOG.md]: done!

**Review by lpil — APPROVED** [review]
Lovely! Thank you!!
