### PR TITLE
Offer unqualify action for type aliases

### LINKED ISSUE #4961: LSP offers incorrect unqualify code action for nested types.
```
pub fn add_event_listener(
  name: String,
  decoder: Decoder(event.Handler(msg)),
                         ^
) -> Effect(msg)
```

If I list the code actions available when my cursor is at the position above indicated by `^`, i see:

> Qualify `Decoder` as `decode.Decoder`

but i would expect to see:

> Unqualify `event.Handler`

this is confusing and wrong.

### PR DESCRIPTION
**Pull request by giacomocavalieri**
This PR closes #4961
The problem was due to the language server not dealing correctly with type aliases.
I've took the chance to add a few comments as the code was not super clear to me before.

### CODE REVIEW

File: compiler-core/src/language_server/code_action.rs [hunk 1]
```diff
@@ -1369,21 +1369,26 @@ impl QualifiedConstructor<'_> {
...
+pub struct QualifiedToUnqualifiedImportFirstPass<'a, IO> {
     module: &'a Module,
+    compiler: &'a LspProjectCompiler<FileSystemProxy<IO>>,
     params: &'a CodeActionParams,
     line_numbers: &'a LineNumbers,
     qualified_constructor: Option<QualifiedConstructor<'a>>,
 }
 
-impl<'a> QualifiedToUnqualifiedImportFirstPass<'a> {
+impl<'a, IO: FileSystemReader + FileSystemWriter + BeamCompiler + CommandExecutor + Clone>
```
Comment (lpil) [inline compiler-core/src/language_server/code_action.rs]: It doesn't look like it compiles the project or reads files or anything, so these could be removed?

I don't think code action classes should ever get any IO capabilities

Comment (giacomocavalieri) [reply compiler-core/src/language_server/code_action.rs]: Yeah seems like we've overlooked this, I've removed the IO capabilities from all actions and the completer as well!
