### PR TITLE
Fix extract variable used on records with 0 arity

### LINKED ISSUE #5629: Extract variable code action does not work for variants with no fields
Image

### PR DESCRIPTION
**Pull request by giacomocavalieri**
This PR closes #5629

- [X] The changes in this PR have been discussed beforehand in an issue
- [X] The issue for this PR has been linked
- [X] Tests have been added for new behaviour
- [X] The changelog has been updated for any user-facing changes

### CODE REVIEW

File: language-server/src/code_action.rs [hunk 1]
```diff
@@ -3568,6 +3603,15 @@ impl<'ast> ast::visit::Visit<'ast> for ExtractVariable<'ast> {
...
                 });
             }
+
+            // Expressions that don't make sense to extract
+            TypedExpr::Panic { .. }
+            | TypedExpr::Echo { .. }
+            | TypedExpr::Block { .. }
+            | TypedExpr::ModuleSelect { .. }
+            | TypedExpr::Invalid { .. }
+            | TypedExpr::PositionalAccess { .. }
```
Comment (lpil) [inline language-server/src/code_action.rs:3613]: I think extracting positional access and module select could make sense? I might want to extract a long chain of them to a variable for clarity, like `one.two.three.four`

Comment (giacomocavalieri) [reply language-server/src/code_action.rs:3613]: That's what the `TypedExpr::RecordAccess` represents, module select is for calling a function `list.map`, I don't think that extracting it ever makes much sense, for example:
```
list.map([], int.parse)
//           ^^^ Extract
// Producing:
let function = int.parse
list.map([], function)
```
And `PositionalAccess` is generated internally for unlabelled fields.
We already support your example, I've added a couple of tests just to make sure!

Comment (lpil) [reply language-server/src/code_action.rs:3613]: Oh doh! I mixed up record and module 🤦

**Review by lpil — APPROVED** [review]
Thank you!!
