### PR TITLE
Show whole pipeline in return type mismatch errors

### LINKED ISSUE #1378: Pipeline error message showing incorrect code
```rust
import gleam/string

fn get_data() -> String {
  ""
  |> string.split(on: ",")
}
```
```
error: Type mismatch
  ┌─ src/thingy.gleam:4:3
  │
4 │   ""
  │   ^^

The type of this returned value doesn't match the return type 
annotation of this function.

Expected type:

    String

Found type:

    List(String)
```

### PR DESCRIPTION
**Pull request by michallepicki**
Closes #1378

### CODE REVIEW

File: compiler-core/src/type_/pipe.rs [hunk 1]
```diff
@@ -18,17 +18,24 @@ impl<'a, 'b, 'c> PipeTyper<'a, 'b, 'c> {
         expressions: Vec1<UntypedExpr>,
     ) -> Result<TypedExpr, Error> {
         let size = expressions.len();
-        let mut expressions = expressions.into_iter();
-        let first = expr_typer.infer(
+        let end = expressions
+            .iter()
+            .last()
```
Comment (lpil) [inline compiler-core/src/type_/pipe.rs:23]: Tiny tiny nit but I think we can call the `.last()` methon on a slice to avoid iterating over the prior expressions.

https://doc.rust-lang.org/std/primitive.slice.html#method.last

**Review by lpil — APPROVED** [review]
Thank you

File: compiler-core/src/type_/pipe.rs (hunk 1 above)
Comment (michallepicki) [reply compiler-core/src/type_/pipe.rs]: Updated!

**Comment by lpil** [comment]
💜
