### PR TITLE
fix excessive `gleam.mjs` generation

### LINKED ISSUE #3178: `gleam build` generates `gleam.mjs` and `gleam.d.mts` even if they already exist
Here are some of the logs from `vite`:

```
CHANGED build/dev/javascript/gleam_stdlib/gleam.mjs
CHANGED build/dev/javascript/gleam_stdlib/gleam.d.mts
CHANGED build/dev/javascript/ranger/gleam.mjs
CHANGED build/dev/javascript/ranger/gleam.d.mts
CHANGED build/dev/javascript/birl/gleam.mjs
CHANGED build/dev/javascript/birl/gleam.d.mts
CHANGED build/dev/javascript/gleam_javascript/gleam.mjs
CHANGED build/dev/javascript/gleam_javascript/gleam.d.mts
CHANGED build/dev/javascript/gleam_json/gleam.mjs
CHANGED build/dev/javascript/gleam_json/gleam.d.mts
CHANGED build/dev/javascript/gleeunit/gleam.mjs
CHANGED build/dev/javascript/gleeunit/gleam.d.mts
CHANGED build/dev/javascript/gluid/gleam.mjs
CHANGED build/dev/javascript/gluid/gleam.d.mts
CHANGED build/dev/javascript/juno/gleam.mjs
CHANGED build/dev/javascript/juno/gleam.d.mts
```

Since I use `vite-gleam`, which builds on changes detected by `vite`, this results in an infinite loop. Top-level application files depend on those `gleam.mjs`s, thus marked as changed themselves, and then they trigger another build.

This is troublesome in another way -- since HMR loads duplicates of a changed file (see vitejs/vite#645), all the code that relies on `instanceof` fails. This is because an object that was created before the underlying library file was replaced is not an `instanceof` the class defined in the new file. Example of failing code:

```gleam
let definitely_something = Some(5)

fn make_result() {
  definitely_something
  |> option.to_result
}

// this returns an Error if called after HMR was fired for option.mjs, which is always the case with this bug
make_result()
```

I've compiled 9ba060ddf12fd01302606b269d5fde0c2ffa6c08 to check if the issue exists and it does.

NixOS 23.11

### PR DESCRIPTION
**Pull request by ofekd**
This patch fixes excessive generation by checking if `modules` is empty.

Two other possible solutions have been ruled out:

- Checking for file existence may result in not updating outdated files
- Comparing contents is slow

closes #3178

### CODE REVIEW

File: compiler-core/src/codegen.rs [hunk 1]
```diff
@@ -186,7 +186,11 @@ impl<'a> JavaScript<'a> {
             }
             self.js_module(writer, module, &js_name)?
         }
-        self.write_prelude(writer)?;
+
+        if !modules.is_empty() {
+            self.write_prelude(writer)?;
+        }
```
Comment (lpil) [inline compiler-core/src/codegen.rs:192]: Could you add a comment explaining what this is doing and why please. Thank you

**Review by lpil — COMMENTED** [review]
Nice!!

**Comment by ofekd** [comment]
All done, thanks for reviewing

**Review by lpil — APPROVED** [review]
Thank you
