### PR TITLE
Fix bit pattern size usage tracking

### LINKED ISSUE #5599: Constants referenced only in bit array size segments are missing from compiled JavaScript.
A playground reproduction can be found here: https://playground.gleam.run/#N4IgbgpgTgzglgewHYgFwEYA0IDGyAuES+auyM+ABDAgLYQD68AXhJQLyUBMAOkn3iQVKAIzj4YHSgB5pWLpgDMmACwA+NXz4AHAK4jKAMySVaAQzhIAFAEpKwPpUo4zMNmIn3HTmdIAeqCIAnoQwALQsEFY09ExwrDaYlAyB4jAalGFqXiY+ThA4ABYIlH7eeQBycAA25ZQAvnV1DJnZVbW5jUhdIPVAA==

Note the runtime error:

> ReferenceError: Can't find variable: some_size

Simply referencing `some_size` outside of the bit array pattern is enough to resolve the error.

### LINKED ISSUE #5600: Constants referenced only in bit array size segments produce incorrect "unused constant" warnings
See the playground link for a reproduction: https://playground.gleam.run/#N4IgbgpgTgzglgewHYgFwEYA0IDGyAuES+auyM+ABDAgLYQD68AXhJQLyUBMAOkn3iQVKAIzj4YHSgB5pWLpgDMmACwA+NXz4AHAK4jKAMySVaAQzhIAFAEpKwPpUo4zMNmIn3HTmdIAeqCIAnoQwALQsEFY09ExwrDaYlAyB4jAalGFqXiY+ThA4ABYIlH7eeQBycAA25ZQAvnV1DJnZVbW5jUhdIPVAA==

The following warning is produced:

```
warning: Unused private constant
  ┌─ /src/main.gleam:1:1
  │
1 │ const some_size = 2
  │ ^^^^^^^^^^^^^^^ This private constant is never used

Hint: You can safely remove it.
```

But it is referenced in the code:

```gleam
pub fn main() {
  case bits {
    <<x:bytes-size(some_size), _:bits>> -> {
      ...
```

### PR DESCRIPTION
**Pull request by lpil**
Closes https://github.com/gleam-lang/gleam/issues/5600
Closes https://github.com/gleam-lang/gleam/issues/5599

- [x] The changes in this PR have been discussed beforehand in an issue
- [x] The issue for this PR has been linked
- [x] Tests have been added for new behaviour
- [x] The changelog has been updated for any user-facing changes

### CODE REVIEW

**Comment by ankddev** [comment]
Looks like you forgot to commit snapshot! And Clippy is failing

**Comment by lpil** [comment]
oops!

**Review by ankddev — APPROVED** [review]

File: compiler-core/src/type_/pattern.rs [hunk 1]
```diff
@@ -1383,6 +1383,21 @@ impl<'a, 'b> PatternTyper<'a, 'b> {
...
 
+                match &constructor.variant {
+                    ValueConstructorVariant::LocalVariable { .. } => (),
+                    ValueConstructorVariant::ModuleConstant { module, name, .. }
+                    | ValueConstructorVariant::ModuleFn { name, module, .. }
+                    | ValueConstructorVariant::Record { name, module, .. } => {
+                        self.environment.references.register_value_reference(
+                            module.clone(),
+                            name.clone(),
+                            name,
```
Comment (GearsDatapacks) [inline compiler-core/src/type_/pattern.rs]: I believe this is the wrong `name`. This parameter needs the name used in the source code rather than the original name of the value (you'll need to rename this variable as you've shadowed `name` here)
To add a test for this you need to import a constant unqualified and reference it here.

Comment (lpil) [reply compiler-core/src/type_/pattern.rs]: oops, I thought I was doing that! Thank you
