### PR TITLE
Fix record updates discarding unlabelled fields

### LINKED ISSUE #5195: Record update with mixed positional and named fields drops positional fields
The following code

```gleam
pub type T {
  T(Int, a: Int, b: Int)
}

pub fn main() {
  let t = T(1, 2, 3)
  echo T(..t, a: 4)
}
```

outputs in JavaScript (the field b should not be Nil)

```
src/main.gleam:7
T(4, a: 3, b: Nil)
```

but should be

```
src/main.gleam:7
T(1, a: 4, b: 3)
```

and outputs in Erlang (the field b should be present)

```
src/main.gleam:7
T(4, 3)
```

but should be

```
src/main.gleam:7
T(1, 4, 3)
```

I'm using gleam 1.13.0.

### PR DESCRIPTION
**Pull request by GearsDatapacks**
Fixes #5195 

This ended up being a much bigger change than I anticipated

### CODE REVIEW

File: compiler-core/src/type_/tests/errors.rs [hunk 1]
```diff
@@ -3383,3 +3383,19 @@ pub type Dict(key, value) {
 "#
     );
 }
+
+#[test]
+fn generic_unlabelled_field_in_updated_record_wrong_type() {
+    assert_module_error!(
```
Comment (abs0luty) [inline compiler-core/src/type_/tests/errors.rs:3389]: This test looks like it should not raise an error because generic type respecialization should resolve it, which matches the earlier point in https://github.com/gleam-lang/gleam/pull/5061#discussion_r2600044018:

```gleam
pub type Wibble(a) {
  Wibble(a, b: Int, c: a)
}

const w = Wibble(1, 2, 3)
const w2 = Wibble(..w, c: False) // Wibble(1, 2, False)
```

Changing how unlabelled fields are handled shouldn't alter this behaviour?

**Review by abs0luty — COMMENTED** [review]
Left a note!

File: compiler-core/src/type_/tests/errors.rs (hunk 1 above)
Comment (GearsDatapacks) [reply compiler-core/src/type_/tests/errors.rs:3389]: No, because the first positional field is of type `a` also, which is not being updated here, leading to a conflicting `a` type. The first field is of type `Int`, while `c` is of type `Bool`.

Comment (abs0luty) [reply compiler-core/src/type_/tests/errors.rs:3389]: You are right, and I am not sure how I missed it! We would need to duplicate this test for constant records as well and the constant version would not produce any errors against expectations. Do you want to dig into it here?

Comment (GearsDatapacks) [reply compiler-core/src/type_/tests/errors.rs:3389]: Probably worth opening a separate issue, as they are largely unrelated pieces of code

File: compiler-core/src/error.rs [hunk 2]
```diff
@@ -810,6 +810,15 @@ fn did_you_mean(name: &str, options: &[EcoString]) -> Option<String> {
         .map(|(option, _)| format!("Did you mean `{option}`?"))
 }
 
+fn to_ordinal(value: u32) -> String {
+    match value % 10 {
+        1 => format!("{value}st"),
+        2 => format!("{value}nd"),
```
Comment (lpil) [inline compiler-core/src/error.rs:818]: 11st -> 11th
12nd -> 12th
13rd -> 13th

File: compiler-core/src/ast/typed.rs [hunk 3]
```diff
@@ -105,6 +105,7 @@ pub enum TypedExpr {
         index: u64,
         record: Box<Self>,
         documentation: Option<EcoString>,
+        kind: RecordAccessKind,
```
Comment (lpil) [inline compiler-core/src/ast/typed.rs]: Record access can never be positional- the data structure mandates that the label is always present.

If we need to modify the AST we'll need to do so in a way that doesn't force invalid data to be added to the fields of a variant.

File: compiler-core/src/type_/expression.rs [hunk 4]
```diff
@@ -3363,20 +3371,107 @@ impl<'a, 'b> ExprTyper<'a, 'b> {
...
+
+                        _ => panic!("Type has already checked to be valid"),
+                    }
+                    .expect("Variant has already checked to be valid");
+
+                let type_ = positional_fields
+                    .get(index as usize)
+                    .expect("Field exists")
+                    .clone();
+                let mut type_vars = im::HashMap::new();
```
Comment (lpil) [inline compiler-core/src/type_/expression.rs:3440]: Won't this result in rigid type variables not being respected? Without them being passed in they would be instantiated to an unbound variable instead of remaining generic?

**Review by lpil — COMMENTED** [review]
Thank you! Super fab work!

I've left some Qs inline

File: compiler-core/src/type_/expression.rs (hunk 4 above)
Comment (GearsDatapacks) [reply compiler-core/src/type_/expression.rs:3440]: I'm not sure exactly what you mean by that. I just copied the code that is used for labelled fields.
If you have an example, I can add a test for it

Comment (lpil) [reply compiler-core/src/type_/expression.rs:3440]: I wasn't able to write a test that showed incorrect behaviour, so I guess I'm wrong! :)
