### PR TITLE
Surface diagnostic errors for import cycles

### LINKED ISSUE #3274: Surface diagnostic errors for import cycles
It would be helpful to surface some/all of the import statements causing an import cycle via a diagnostic error. This way the editor does not appear to have started failing to report all diagnostic data from the gleam build tool.

Currently import cycles result in compilation errors like the following:

```
error: Import cycle

The import statements for these modules form a cycle:

    ┌─────┐
    │     thing3
    │     ↓
    │     thing2
    │     ↓
    │     thing
    └─────┘
Gleam doesn't support dependency cycles like these, please break the
cycle to continue.
```

In some editors (nvim, vscode) this error is logged with a popup but results in no other editor response, in zed there is no popup for this output 

It may also be useful for the compiler message to include the code locations of the imports involved

### PR DESCRIPTION
**Pull request by Acepie**
Closes #3274 

Looks up the import location within the module when a cycle error occurs and adds the location to the error. In addition, in order to make this change render, there were updates to the lsp feedback and diagnostic mechanisms to allow for cross file feedback and the rendering of extra labels.

### CODE REVIEW

File: compiler-core/src/build/package_loader.rs [hunk 1]
```diff
@@ -1547,9 +1554,35 @@ fn ensure_gleam_module_does_not_overwrite_standard_erlang_module(input: &Input)
...
+) -> Error {
     match e {
-        dep_tree::Error::Cycle(modules) => Error::ImportCycle { modules },
+        dep_tree::Error::Cycle(modules) => {
+            let mut locations = vec![];
+            for (i, module) in modules.iter().enumerate() {
+                // cycles are in order of reference so get next in list or loop back to first
+                let ind = if i == modules.len() - 1 { 0 } else { i + 1 };
+                let next = modules.get(ind).expect("next module must exist");
+                // HACK: for cached modules we do not have the location of the import
```
Comment (lpil) [inline compiler-core/src/build/package_loader.rs:1568]: We will need to store this information then in this case.

File: compiler-core/src/diagnostic.rs [hunk 2]
```diff
@@ -19,18 +21,37 @@ pub struct Label {
     pub span: SrcSpan,
 }
 
+trait ToCodespanLabel {
```
Comment (lpil) [inline compiler-core/src/diagnostic.rs:24]: No new traits please.

File: compiler-core/src/diagnostic.rs [hunk 3]
```diff
@@ -19,18 +21,37 @@ pub struct Label {
...
+        match &self.text {
+            None => label,
+            Some(text) => label.with_message(text.clone()),
+        }
+    }
+}
+
 #[derive(Debug, Clone, PartialEq, Eq)]
-pub struct Location {
+pub struct ExtraLocation {
```
Comment (lpil) [inline compiler-core/src/diagnostic.rs:43]: It looks like the vast majority of the time the path is the same, so I think location information should be optional.

File: compiler-core/src/error.rs [hunk 4]
```diff
@@ -81,7 +88,10 @@ pub enum Error {
     DuplicateSourceFile { file: String },
 
     #[error("cyclical module imports")]
-    ImportCycle { modules: Vec<EcoString> },
+    ImportCycle {
+        modules: Vec<EcoString>,
+        locations: Vec1<ImportCycleLocationDetails>,
```
Comment (lpil) [inline compiler-core/src/error.rs:93]: Shouldn't this be one vector? It seems they must always be the same length.

File: compiler-core/src/language_server/feedback.rs [hunk 5]
```diff
@@ -123,15 +123,29 @@ impl FeedbackBookKeeper {
...
-                    feedback.append_diagnostic(path, diagnostic);
-                }
-
-                None => {
-                    feedback.append_message(diagnostic);
+            if let Some(l) = &diagnostic.location {
+                _ = self.files_with_errors.insert(l.path.clone());
+                feedback.append_diagnostic(l.path.clone(), diagnostic.clone());
+
+                for extra in &l.extra_labels {
```
Comment (lpil) [inline compiler-core/src/language_server/feedback.rs:130]: This renders the additional information as entirely new diagnostics rather than being part of the first one. This may be OK for imports cycles, but in the duplicate import example there is now a diagnostic that just says "First imported here" with no other context.

It should instead be a nested diagnostic, possibly of a different colour like how hints are displayed.

**Review by lpil — COMMENTED** [review]
Thank you! I've left some notes on how we're approaching the extra information. I think the way it is presented currently is a bit unclear for the user.

File: compiler-core/src/diagnostic.rs (hunk 2 above)
Comment (Acepie) [reply compiler-core/src/diagnostic.rs:24]: oh good call I don't need this anymore. In an old version of this code I had this implemented on the locations

File: compiler-core/src/language_server/feedback.rs (hunk 5 above)
Comment (Acepie) [reply compiler-core/src/language_server/feedback.rs:130]: Yeah that makes sense. The reason I had it like this was that it looks like sub-diagnostics can't be across files in the lsp protocol if I am reading correctly. Lemme change this so the ones in different files are separate diagnostics but the ones in the same file are sub diagnostics

Comment (Acepie) [reply compiler-core/src/language_server/feedback.rs:130]: Oh nevermind I'm totally wrong and misread the protocol 🤦🏽 lemme fix this

File: compiler-core/src/language_server/server.rs [hunk 6]
```diff
@@ -455,15 +456,47 @@ fn diagnostic_to_lsp(diagnostic: Diagnostic) -> Vec<lsp::Diagnostic> {
...
+        .extra_labels
+        .iter()
+        .map(|extra| {
+            let message = extra.label.text.clone().unwrap_or_default();
+            let location = if let Some(path) = &extra.path {
+                let line_numbers = LineNumbers::new(
+                    &extra
+                        .src
+                        .clone()
+                        .expect("different path must have source attached"),
```
Comment (lpil) [inline compiler-core/src/language_server/server.rs:472]: If these should be given together than they should be in the same `Option`

File: compiler-core/src/error.rs [hunk 7]
```diff
@@ -1335,9 +1348,13 @@ Names in a Gleam module must be unique so one will need to be renamed."
                             },
                             path: path.clone(),
                             src: src.clone(),
-                            extra_labels: vec![Label {
-                                text: Some("First imported here".into()),
-                                span: *previous_location,
+                            extra_labels: vec![ExtraLocation {
```
Comment (lpil) [inline compiler-core/src/error.rs:1351]: Perhaps this name as it's not always a location
```suggestion
                            extra_labels: vec![ExtraLabel {
```

**Review by lpil — COMMENTED** [review]
Oh this is looking really very nice!!!

File: compiler-core/src/language_server/server.rs (hunk 6 above)
Comment (Acepie) [reply compiler-core/src/language_server/server.rs:472]: Yeah makes sense I'll combine them into 1 tuple

File: compiler-core/src/error.rs (hunk 7 above)
Comment (Acepie) [reply compiler-core/src/error.rs:1351]: works for me

**Comment by Acepie** [comment]
Alright this should be all good now 👍🏽

**Review by lpil — APPROVED** [review]
Beautiful work!!!
