### PR TITLE
Fix generation of package interface when modules are cached

### LINKED ISSUE #2898: `gleam export package-interface` produces empty modules object
When I run `gleam export package-interface --out <some_path>.json` on any of my packages (tested with simplifile and gsv),
the file produced has an empty object for the modules field as though they were empty packages.
```json
{"name":"gsv","version":"1.4.0","gleam-version-constraint":">= 0.32.0","modules":{}}
```

I checked the package-interface.json in the build directory and it's being correctly produced, so the module info get's lost somehow exporting the file.

I'm on an M2 Mac running the main branch of Gleam. The logs from after the compile stage are pretty sparse
```
Compiled in 0.01s
TRACE writing_file path="/Users/benjaminpeinhardt/Development/Projects/gsv/./file.json"
INFO Successfully completed
```

I'll try and look into this as I bet it's something small or I'm doing something wrong, but if someone beats me to it I won't be upset haha.

### PR DESCRIPTION
**Pull request by GearsDatapacks**
This PR follows on from #3669 and fixes #2898.
It uses partly the same approach of using the `ModuleInterface` (the part which is cached) to generate the package interface, rather than the AST. However, this is implemented in such a way that the cached modules do not need to be cloned when doing so.

### CODE REVIEW

File: compiler-core/src/build/package_compiler.rs [hunk 1]
```diff
@@ -30,6 +30,11 @@ use camino::{Utf8Path, Utf8PathBuf};
 
 use super::{ErlangAppCodegenConfiguration, TargetCodegenConfiguration, Telemetry};
 
+pub struct Compiled {
```
Comment (lpil) [inline compiler-core/src/build/package_compiler.rs:33]: Why is this done? The `Module` struct already contains the name.

File: compiler-core/src/metadata/tests.rs [hunk 2]
```diff
@@ -1557,6 +1630,8 @@ fn type_with_inferred_variant() {
         line_numbers: LineNumbers::new(""),
         src_path: "some_path".into(),
         minimum_required_version: Version::new(0, 1, 0),
+        type_aliases: HashMap::new(),
+        documentation: Vec::new(),
```
Comment (lpil) [inline compiler-core/src/metadata/tests.rs:1634]: Please add some new tests when new functionality is added to the metadata encoding and decoding. This is the area of the codebases that causes the most bugs

File: compiler-core/src/type_.rs [hunk 3]
```diff
@@ -1208,6 +1212,7 @@ impl TypeVar {
 #[derive(Debug, Clone, PartialEq, Eq)]
 pub struct TypeConstructor {
     pub publicity: Publicity,
+    pub opaque: bool,
```
Comment (lpil) [inline compiler-core/src/type_.rs:1215]: This type design means that it is now possible for a type to be private and opaque at the same time, but that shouldn't be possible. Using a bool is also error prone and unclear, it'd need to be a new type. Perhaps opacity could be part of the existing publicity type? That said I'm not immediately into information about the value constructors being recorded here as this is information about the type constructor...

Do you have any thoughts on this? I'm not sure what's best

File: compiler-core/src/type_/fields.rs [hunk 4]
```diff
@@ -201,6 +201,13 @@ impl FieldMap {
             .map(|(label, _position)| label.clone())
             .collect_vec()
     }
+
+    pub fn indices_to_labels(&self) -> HashMap<u32, EcoString> {
```
Comment (lpil) [inline compiler-core/src/type_/fields.rs:205]: Looks like this clone isn't needed from where it is used

**Review by lpil — COMMENTED** [review]
Wonderful!! Thank you! I've left a few questions inline

File: compiler-core/src/type_/fields.rs (hunk 4 above)
Comment (GearsDatapacks) [reply compiler-core/src/type_/fields.rs:205]: Good point, I'll remove it

File: compiler-core/src/type_.rs (hunk 3 above)
Comment (GearsDatapacks) [reply compiler-core/src/type_.rs:1215]: I don't have any immediate thoughts. I'll look at where it's used and try to figure something out

**Comment by GearsDatapacks** [comment]
All your comments/questions should now be resolved. I've moved the `opaque` field to the `TypesVariantConstructors` type as it seemed more appropriate there. I've also used a custom type instead of a bool now.

**Review by lpil — APPROVED** [review]
Thank you!!!
