### PR TITLE
Move "Did you want a Bool" error to analysis step

### LINKED ISSUE #5052: Move the "Did you want a Bool" error to the analysis step
In Gleam a common beginner mistake was to use `true` and `false` instead of `True` and `False` in pattern matching:
```gleam
case is_admin(user) {
  // vv This should be `True`
  true -> admin_dashboard()
  // vv This should be `False`
  false -> page_404()
}
```
So using `true` and `false` in a case expression is a syntax error with a helpful error message:
```
error: Syntax error
  ┌─ /src/main.gleam:5:5
  │
5 │     true -> 1
  │     ^^^^ Did you want a Bool instead of a variable?

See: https://tour.gleam.run/basics/bools/
Hint: In Gleam boolean literals are `True` and `False`.
```
The problem with this being a syntax error is that it stops analysis from happening in the entire module. It would be best if this error was emitted during the analysis phase instead. This requires a couple of changes:
- Remove the `ParseErrorType::LowcaseBooleanPattern` variant and make it a variant of `Error` (in the `compiler_core/src/type_/error.rs` file)
- Once you've done that you should be able to follow the compiler errors to remove the piece of code that's emitting that error in the parsing step
- That same logic that emits the error should be moved to the piece of the compiler that's analysing variable patterns (that will most likely be the `unify` function in the `compiler_core/src/type_/pattern.rs` file, the branch where this should happen is probably the one matching on the `Pattern::Variable` variant)
- And don't forget to add tests in `compiler_core/src/type_/tests.rs` to make sure the error is actually emitted. It should be pretty straightforward to copy one of the other tests using `assert_module_error!` and adapt it with a code snippet producing this error instead

There's other changes that we could make, like being smarter about where this error happens. But that can be a separate issue to keep this nice and approachable for newcomers :)

### PR DESCRIPTION
**Pull request by mxtthias**
Fixes #5052

### CODE REVIEW

**Comment by mxtthias** [comment]
I'm really not sure if I've done this the right way, so any feedback is much appreciated!

File: compiler-core/src/error.rs [hunk 1]
```diff
@@ -3985,6 +3985,22 @@ modules should not import them. Perhaps change `{package}` to a regular dependen
...
                     },
+
+                    TypeError::LowcaseBooleanPattern { location } => Diagnostic {
+                        title: "Lowercase boolean pattern".to_string(),
+                        text: "See: https://tour.gleam.run/basics/bools/".into(),
+                        hint: Some("In Gleam boolean literals are `True` and `False`.".into()),
+                        level: Level::Error,
+                        location: Some(Location {
+                            label: Label {
+                                text: Some("Did you want a Bool instead of a variabel?".into()),
```
Comment (giacomocavalieri) [inline compiler-core/src/error.rs]: Small typo
```suggestion
                                text: Some("Did you want a Bool instead of a variable?".into()),
```

File: compiler-core/src/type_/error.rs [hunk 2]
```diff
@@ -664,6 +664,10 @@ pub enum Error {
         location: SrcSpan,
         name: EcoString,
     },
+
+    LowcaseBooleanPattern {
```
Comment (giacomocavalieri) [inline compiler-core/src/type_/error.rs]: Since you're here could you rename the variant to `LowercaseBooleanPattern`? We are trying to get rid of shorthand names as we come across them, and this one too could be updated

**Comment by mxtthias** [comment]
@giacomocavalieri Thank you for your review! Please let me know if you want me to squash the commits or so.

**Comment by giacomocavalieri** [comment]
Thank you! No need to squash, the only thing we want to avoid is merge commits, anything else is totally fine 😊

**Comment by giacomocavalieri** [comment]
Looks great to me, now it just needs Louis' review

File: compiler-core/src/type_/error.rs [hunk 3]
```diff
@@ -664,6 +664,10 @@ pub enum Error {
         location: SrcSpan,
         name: EcoString,
     },
+
+    LowercaseBooleanPattern {
```
Comment (lpil) [inline compiler-core/src/type_/error.rs]:
```suggestion
    LowercaseBoolPattern {
```

File: compiler-core/src/error.rs [hunk 4]
```diff
@@ -3984,6 +3984,22 @@ modules should not import them. Perhaps change `{package}` to a regular dependen
                             extra_labels: vec![],
                         }),
                     },
+
+                    TypeError::LowercaseBooleanPattern { location } => Diagnostic {
+                        title: "Lowercase boolean pattern".to_string(),
```
Comment (lpil) [inline compiler-core/src/error.rs]:
```suggestion
                        title: "Lowercase bool pattern".to_string(),
```

File: compiler-core/src/error.rs [hunk 5]
```diff
@@ -3984,6 +3984,22 @@ modules should not import them. Perhaps change `{package}` to a regular dependen
...
+                        text: "See: https://tour.gleam.run/basics/bools/".into(),
+                        hint: Some("In Gleam boolean literals are `True` and `False`.".into()),
```
Comment (lpil) [inline compiler-core/src/error.rs]:
```suggestion
                        hint: Some("In Gleam bool literals are `True` and `False`.".into()),
```

File: compiler-core/src/error.rs [hunk 6]
```diff
@@ -3984,6 +3984,22 @@ modules should not import them. Perhaps change `{package}` to a regular dependen
...
+                        level: Level::Error,
+                        location: Some(Location {
+                            label: Label {
+                                text: Some("Did you want a Bool instead of a variable?".into()),
```
Comment (lpil) [inline compiler-core/src/error.rs]:
```suggestion
                                text: Some("This is not a bool".into()),
```

File: CHANGELOG.md [hunk 7]
```diff
@@ -15,6 +15,11 @@
   on the Erlang target.
   ([Giacomo Cavalieri](https://github.com/giacomocavalieri))
 
+- The "Did you want a Bool" error is no longer a syntax error, but instead a
```
Comment (lpil) [inline CHANGELOG.md]:
```suggestion
- The lowercase bool pattern error is no longer a syntax error, but instead a
```

**Comment by mxtthias** [comment]
@lpil Thank you for the comments! Really appreciate help with the wording!

**Comment by giacomocavalieri** [comment]
Hello! This has conflicts with the main branch, would you mind rebasing?
